package net.errorcraft.itematic.item;

import net.minecraft.item.Item;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.util.Identifier;

public class ItematicItemTags {
    public static final TagKey<Item> REPAIRS_LEATHER_ARMOR = of("repairs_leather_armor");
    public static final TagKey<Item> REPAIRS_CHAINMAIL_ARMOR = of("repairs_chainmail_armor");
    public static final TagKey<Item> REPAIRS_IRON_ARMOR = of("repairs_iron_armor");
    public static final TagKey<Item> REPAIRS_GOLDEN_ARMOR = of("repairs_golden_armor");
    public static final TagKey<Item> REPAIRS_DIAMOND_ARMOR = of("repairs_diamond_armor");
    public static final TagKey<Item> REPAIRS_NETHERITE_ARMOR = of("repairs_netherite_armor");
    public static final TagKey<Item> REPAIRS_TURTLE_ARMOR = of("repairs_turtle_armor");

    public static final TagKey<Item> BOW_AMMUNITION = of("bow_ammunition");
    public static final TagKey<Item> CROSSBOW_AMMUNITION = of("crossbow_ammunition");

    public static final TagKey<Item> PIG_TEMPT_ITEMS = of("pig_tempt_items");
    public static final TagKey<Item> VILLAGER_GATHERABLE_ITEMS = of("villager_gatherable_items");
    public static final TagKey<Item> FARMER_VILLAGER_GATHERABLE_ITEMS = of("farmer_villager_gatherable_items");

    public static final TagKey<Item> OAK_BUILDING_BLOCKS = of("item_group/oak_building_blocks");
    public static final TagKey<Item> SPRUCE_BUILDING_BLOCKS = of("item_group/spruce_building_blocks");
    public static final TagKey<Item> BIRCH_BUILDING_BLOCKS = of("item_group/birch_building_blocks");
    public static final TagKey<Item> JUNGLE_BUILDING_BLOCKS = of("item_group/jungle_building_blocks");
    public static final TagKey<Item> ACACIA_BUILDING_BLOCKS = of("item_group/acacia_building_blocks");
    public static final TagKey<Item> DARK_OAK_BUILDING_BLOCKS = of("item_group/dark_oak_building_blocks");
    public static final TagKey<Item> MANGROVE_BUILDING_BLOCKS = of("item_group/mangrove_building_blocks");
    public static final TagKey<Item> CHERRY_BUILDING_BLOCKS = of("item_group/cherry_building_blocks");
    public static final TagKey<Item> BAMBOO_BUILDING_BLOCKS = of("item_group/bamboo_building_blocks");
    public static final TagKey<Item> CRIMSON_BUILDING_BLOCKS = of("item_group/crimson_building_blocks");
    public static final TagKey<Item> WARPED_BUILDING_BLOCKS = of("item_group/warped_building_blocks");
    public static final TagKey<Item> WOODEN_BUILDING_BLOCKS = of("item_group/wooden_building_blocks");
    public static final TagKey<Item> STONE_BUILDING_BLOCKS = of("item_group/stone_building_blocks");
    public static final TagKey<Item> COBBLESTONE_BUILDING_BLOCKS = of("item_group/cobblestone_building_blocks");
    public static final TagKey<Item> MOSSY_COBBLESTONE_BUILDING_BLOCKS = of("item_group/mossy_cobblestone_building_blocks");
    public static final TagKey<Item> SMOOTH_STONE_BUILDING_BLOCKS = of("item_group/smooth_stone_building_blocks");
    public static final TagKey<Item> STONE_BRICK_BUILDING_BLOCKS = of("item_group/stone_brick_building_blocks");
    public static final TagKey<Item> MOSSY_STONE_BRICK_BUILDING_BLOCKS = of("item_group/mossy_stone_brick_building_blocks");
    public static final TagKey<Item> GRANITE_BUILDING_BLOCKS = of("item_group/granite_building_blocks");
    public static final TagKey<Item> POLISHED_GRANITE_BUILDING_BLOCKS = of("item_group/polished_granite_building_blocks");
    public static final TagKey<Item> DIORITE_BUILDING_BLOCKS = of("item_group/diorite_building_blocks");
    public static final TagKey<Item> POLISHED_DIORITE_BUILDING_BLOCKS = of("item_group/polished_diorite_building_blocks");
    public static final TagKey<Item> ANDESITE_BUILDING_BLOCKS = of("item_group/andesite_building_blocks");
    public static final TagKey<Item> POLISHED_ANDESITE_BUILDING_BLOCKS = of("item_group/polished_andesite_building_blocks");
    public static final TagKey<Item> COBBLED_DEEPSLATE_BUILDING_BLOCKS = of("item_group/cobbled_deepslate_building_blocks");
    public static final TagKey<Item> POLISHED_DEEPSLATE_BUILDING_BLOCKS = of("item_group/polished_deepslate_building_blocks");
    public static final TagKey<Item> DEEPSLATE_BRICK_BUILDING_BLOCKS = of("item_group/deepslate_brick_building_blocks");
    public static final TagKey<Item> DEEPSLATE_TILES_BUILDING_BLOCKS = of("item_group/deepslate_tiles_building_blocks");
    public static final TagKey<Item> TUFF_BUILDING_BLOCKS = of("item_group/tuff_building_blocks");
    public static final TagKey<Item> BRICK_BUILDING_BLOCKS = of("item_group/brick_building_blocks");
    public static final TagKey<Item> MUD_BRICK_BUILDING_BLOCKS = of("item_group/mud_brick_building_blocks");
    public static final TagKey<Item> SANDSTONE_BUILDING_BLOCKS = of("item_group/sandstone_building_blocks");
    public static final TagKey<Item> SMOOTH_SANDSTONE_BUILDING_BLOCKS = of("item_group/smooth_sandstone_building_blocks");
    public static final TagKey<Item> CUT_SANDSTONE_BUILDING_BLOCKS = of("item_group/cut_sandstone_building_blocks");
    public static final TagKey<Item> RED_SANDSTONE_BUILDING_BLOCKS = of("item_group/red_sandstone_building_blocks");
    public static final TagKey<Item> SMOOTH_RED_SANDSTONE_BUILDING_BLOCKS = of("item_group/smooth_red_sandstone_building_blocks");
    public static final TagKey<Item> CUT_RED_SANDSTONE_BUILDING_BLOCKS = of("item_group/cut_red_sandstone_building_blocks");
    public static final TagKey<Item> PRISMARINE_BUILDING_BLOCKS = of("item_group/prismarine_building_blocks");
    public static final TagKey<Item> PRISMARINE_BRICK_BUILDING_BLOCKS = of("item_group/prismarine_brick_building_blocks");
    public static final TagKey<Item> DARK_PRISMARINE_BUILDING_BLOCKS = of("item_group/dark_prismarine_building_blocks");
    public static final TagKey<Item> NETHER_BRICK_BUILDING_BLOCKS = of("item_group/nether_brick_building_blocks");
    public static final TagKey<Item> RED_NETHER_BRICK_BUILDING_BLOCKS = of("item_group/red_nether_brick_building_blocks");
    public static final TagKey<Item> BASALT_BUILDING_BLOCKS = of("item_group/basalt_building_blocks");
    public static final TagKey<Item> BLACKSTONE_BUILDING_BLOCKS = of("item_group/blackstone_building_blocks");
    public static final TagKey<Item> POLISHED_BLACKSTONE_BUILDING_BLOCKS = of("item_group/polished_blackstone_building_blocks");
    public static final TagKey<Item> POLISHED_BLACKSTONE_BRICK_BUILDING_BLOCKS = of("item_group/polished_blackstone_brick_building_blocks");
    public static final TagKey<Item> END_STONE_BRICK_BUILDING_BLOCKS = of("item_group/end_stone_brick_building_blocks");
    public static final TagKey<Item> PURPUR_BUILDING_BLOCKS = of("item_group/purpur_building_blocks");
    public static final TagKey<Item> STONE_LIKE_BUILDING_BLOCKS = of("item_group/stone_like_building_blocks");
    public static final TagKey<Item> IRON_BUILDING_BLOCKS = of("item_group/iron_building_blocks");
    public static final TagKey<Item> GOLD_BUILDING_BLOCKS = of("item_group/gold_building_blocks");
    public static final TagKey<Item> QUARTZ_BUILDING_BLOCKS = of("item_group/quartz_building_blocks");
    public static final TagKey<Item> SMOOTH_QUARTZ_BUILDING_BLOCKS = of("item_group/smooth_quartz_building_blocks");
    public static final TagKey<Item> COPPER_BUILDING_BLOCKS = of("item_group/copper_building_blocks");
    public static final TagKey<Item> EXPOSED_COPPER_BUILDING_BLOCKS = of("item_group/exposed_copper_building_blocks");
    public static final TagKey<Item> WEATHERED_COPPER_BUILDING_BLOCKS = of("item_group/weathered_copper_building_blocks");
    public static final TagKey<Item> OXIDIZED_COPPER_BUILDING_BLOCKS = of("item_group/oxidized_copper_building_blocks");
    public static final TagKey<Item> WAXED_COPPER_BUILDING_BLOCKS = of("item_group/waxed_copper_building_blocks");
    public static final TagKey<Item> WAXED_EXPOSED_COPPER_BUILDING_BLOCKS = of("item_group/waxed_exposed_copper_building_blocks");
    public static final TagKey<Item> WAXED_WEATHERED_COPPER_BUILDING_BLOCKS = of("item_group/waxed_weathered_copper_building_blocks");
    public static final TagKey<Item> WAXED_OXIDIZED_COPPER_BUILDING_BLOCKS = of("item_group/waxed_oxidized_copper_building_blocks");
    public static final TagKey<Item> COPPER_LIKE_BUILDING_BLOCKS = of("item_group/copper_like_building_blocks");
    public static final TagKey<Item> WOOL = of("item_group/wool");
    public static final TagKey<Item> WOOL_CARPETS = of("item_group/wool_carpets");
    public static final TagKey<Item> TERRACOTTA = of("item_group/terracotta");
    public static final TagKey<Item> CONCRETE = of("item_group/concrete");
    public static final TagKey<Item> CONCRETE_POWDER = of("item_group/concrete_powder");
    public static final TagKey<Item> GLAZED_TERRACOTTA = of("item_group/glazed_terracotta");
    public static final TagKey<Item> GLASS = of("item_group/glass");
    public static final TagKey<Item> GLASS_PANES = of("item_group/glass_panes");
    public static final TagKey<Item> ITEM_GROUP_SHULKER_BOXES = of("item_group/shulker_boxes");
    public static final TagKey<Item> BEDS = of("item_group/beds");
    public static final TagKey<Item> CANDLES = of("item_group/candles");
    public static final TagKey<Item> BANNERS = of("item_group/banners");
    public static final TagKey<Item> GRASS_LIKE_BLOCKS = of("item_group/grass_like_blocks");
    public static final TagKey<Item> DIRT_LIKE_BLOCKS = of("item_group/dirt_like_blocks");
    public static final TagKey<Item> SAND_BLOCKS = of("item_group/sand_blocks");
    public static final TagKey<Item> ICE_BLOCKS = of("item_group/ice_blocks");
    public static final TagKey<Item> SNOW_BLOCKS = of("item_group/snow_blocks");
    public static final TagKey<Item> MOSS_BLOCKS = of("item_group/moss_blocks");
    public static final TagKey<Item> STONE_LIKE_BLOCKS = of("item_group/stone_like_blocks");
    public static final TagKey<Item> NETHER_BLOCKS = of("item_group/nether_blocks");
    public static final TagKey<Item> GOLD_OVERWORLD_ORES = of("gold_overworld_ores");
    public static final TagKey<Item> ORE_LIKE_BLOCKS = of("item_group/ore_like_blocks");
    public static final TagKey<Item> AMETHYST_BLOCKS = of("item_group/amethyst_blocks");
    public static final TagKey<Item> LOG_LIKE_BLOCKS = of("item_group/log_like_blocks");
    public static final TagKey<Item> LEAVES = of("item_group/leaves");
    public static final TagKey<Item> MUSHROOM_LIKE_BLOCKS = of("item_group/mushroom_like_blocks");
    public static final TagKey<Item> SAPLINGS = of("item_group/saplings");
    public static final TagKey<Item> PLANTS = of("item_group/plants");
    public static final TagKey<Item> EGG_LIKE_BLOCKS = of("item_group/egg_like_blocks");
    public static final TagKey<Item> CORAL_BLOCKS = of("item_group/coral_blocks");
    public static final TagKey<Item> CORAL = of("item_group/coral");
    public static final TagKey<Item> CORAL_FANS = of("item_group/coral_fans");
    public static final TagKey<Item> SEEDS = of("item_group/seeds");
    public static final TagKey<Item> WATER_BLOCKS = of("item_group/water_blocks");
    public static final TagKey<Item> PUMPKINS = of("item_group/pumpkins");
    public static final TagKey<Item> FROGLIGHTS = of("item_group/froglights");
    public static final TagKey<Item> SCULK = of("item_group/sculk");
    public static final TagKey<Item> TORCHES = of("item_group/torches");
    public static final TagKey<Item> LANTERNS = of("item_group/lanterns");
    public static final TagKey<Item> LIGHT_EMITTING_BLOCKS = of("item_group/light_emitting_blocks");
    public static final TagKey<Item> SIGNS = of("item_group/signs");
    public static final TagKey<Item> HEADS = of("item_group/heads");
    public static final TagKey<Item> INFESTED_BLOCKS = of("item_group/infested_blocks");
    public static final TagKey<Item> RAILS = of("item_group/rails");
    public static final TagKey<Item> MINECARTS = of("item_group/minecarts");
    public static final TagKey<Item> TOOLS = of("item_group/tools");
    public static final TagKey<Item> BUCKETS = of("item_group/buckets");
    public static final TagKey<Item> BUNDLES = of("item_group/bundles");
    public static final TagKey<Item> BOATS = of("item_group/boats");
    public static final TagKey<Item> MUSIC_DISCS = of("item_group/music_discs");
    public static final TagKey<Item> SWORDS = of("item_group/swords");
    public static final TagKey<Item> AXES = of("item_group/axes");
    public static final TagKey<Item> ARMOR = of("item_group/armor");
    public static final TagKey<Item> HORSE_ARMOR = of("item_group/horse_armor");
    public static final TagKey<Item> FOOD = of("item_group/food");
    public static final TagKey<Item> DYES = of("item_group/dyes");
    public static final TagKey<Item> BREWING_INGREDIENTS = of("item_group/brewing_ingredients");
    public static final TagKey<Item> BANNER_PATTERNS = of("item_group/banner_patterns");
    public static final TagKey<Item> SMITHING_TEMPLATES = of("item_group/smithing_templates");
    public static final TagKey<Item> SPAWNERS = of("item_group/spawners");

    public static final TagKey<Item> BANNED_BUNDLE_ITEMS = of("banned_bundle_items");
    public static final TagKey<Item> SHULKER_BOXES = of("shulker_boxes");

    public static final TagKey<Item> PREVENTS_MINING_IN_CREATIVE = of("prevents_mining_in_creative");
    public static final TagKey<Item> PREVENTS_TAKING_POTTED_ITEM_OUT = of("prevents_taking_potted_item_out");

    private ItematicItemTags() {}

    private static TagKey<Item> of(String id) {
        return TagKey.of(RegistryKeys.ITEM, Identifier.ofVanilla(id));
    }
}
