package errorcraft.itematic.item;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import errorcraft.itematic.enchantment.EnchantmentTags;
import errorcraft.itematic.item.armor.ArmorMaterial;
import errorcraft.itematic.item.armor.ArmorMaterialKeys;
import errorcraft.itematic.item.armor.ArmorMaterials;
import errorcraft.itematic.item.component.ItemComponentSet;
import errorcraft.itematic.item.component.components.*;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.EquipmentSlot;
import net.minecraft.item.*;
import net.minecraft.registry.*;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.util.Identifier;

public class ItemUtil {
    public static final Codec<Item> CODEC = RecordCodecBuilder.create((instance) -> instance.group(
        ItemBase.CODEC.fieldOf("base").forGetter(Item::getItemBase),
        ItemComponentSet.CODEC.fieldOf("components").forGetter(Item::getComponents)
    ).apply(instance, ItemUtil::create));

    public static void bootstrap(Registerable<Item> registerable) {
        RegistryEntryLookup<ArmorMaterial> armorMaterials = registerable.getRegistryLookup(ArmorMaterials.ARMOR_MATERIAL_KEY);
        RegistryEntryLookup<Item> items = registerable.getRegistryLookup(RegistryKeys.ITEM);

        registerable.register(ItemKeys.AIR, create(new ItemBase(ItemBaseDisplay.Builder.forBlock(ItemKeys.AIR).build(), 64)));
        registerable.register(ItemKeys.STONE, create(new ItemBase(ItemBaseDisplay.Builder.forBlock(ItemKeys.STONE).build(), 64), ItemComponentSet.builder().with(new BlockItemComponent(Blocks.STONE)).build()));
        registerable.register(ItemKeys.GRASS_BLOCK, create(new ItemBase(ItemBaseDisplay.Builder.forBlock(ItemKeys.GRASS_BLOCK).build(), 64), ItemComponentSet.builder().with(new BlockItemComponent(Blocks.GRASS_BLOCK)).build()));
        registerable.register(ItemKeys.COBBLESTONE, create(new ItemBase(ItemBaseDisplay.Builder.forBlock(ItemKeys.COBBLESTONE).build(), 64), ItemComponentSet.builder().with(new BlockItemComponent(Blocks.COBBLESTONE)).build()));
        registerable.register(ItemKeys.OAK_PLANKS, create(new ItemBase(ItemBaseDisplay.Builder.forBlock(ItemKeys.OAK_PLANKS).build(), 64), ItemComponentSet.builder().with(new BlockItemComponent(Blocks.OAK_PLANKS)).build()));
        registerable.register(ItemKeys.SAND, create(new ItemBase(ItemBaseDisplay.Builder.forBlock(ItemKeys.SAND).build(), 64), ItemComponentSet.builder().with(new BlockItemComponent(Blocks.SAND)).build()));
        registerable.register(ItemKeys.GRASS, create(new ItemBase(ItemBaseDisplay.Builder.forBlock(ItemKeys.GRASS).build(), 64), ItemComponentSet.builder().with(new BlockItemComponent(Blocks.GRASS), new CompostableItemComponent(0.3f)).build()));
        registerable.register(ItemKeys.OAK_SLAB, create(new ItemBase(ItemBaseDisplay.Builder.forBlock(ItemKeys.OAK_SLAB).build(), 64), ItemComponentSet.builder().with(new BlockItemComponent(Blocks.OAK_SLAB)).build()));
        registerable.register(ItemKeys.SNOW, create(new ItemBase(ItemBaseDisplay.Builder.forBlock(ItemKeys.SNOW).build(), 64), ItemComponentSet.builder().with(new BlockItemComponent(Blocks.SNOW)).build()));
        registerable.register(ItemKeys.BARRIER, create(new ItemBase(ItemBaseDisplay.Builder.forBlock(ItemKeys.BARRIER).build(), 64), ItemComponentSet.builder().with(new BlockItemComponent(Blocks.BARRIER)).build()));
        registerable.register(ItemKeys.REDSTONE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.REDSTONE).build(), 64), ItemComponentSet.builder().with(new BlockItemComponent(Blocks.REDSTONE_WIRE)).build()));
        registerable.register(ItemKeys.APPLE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.APPLE).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.APPLE)).with(new CompostableItemComponent(0.65f)).build()));
        registerable.register(ItemKeys.COAL, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.COAL).build(), 64), ItemComponentSet.builder().with(new FuelItemComponent(1600)).build()));
        registerable.register(ItemKeys.DIAMOND, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.DIAMOND).build(), 64)));
        registerable.register(ItemKeys.LAPIS_LAZULI, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.LAPIS_LAZULI).build(), 64)));
        registerable.register(ItemKeys.IRON_INGOT, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.IRON_INGOT).build(), 64)));
        registerable.register(ItemKeys.GOLD_INGOT, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.GOLD_INGOT).build(), 64)));
        registerable.register(ItemKeys.NETHERITE_INGOT, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.NETHERITE_INGOT).build(), 64)));
        registerable.register(ItemKeys.WOODEN_SWORD, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.WOODEN_SWORD).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.WOOD, 2)).with(new WeaponItemComponent(1), EnchantableItemComponent.enchants(ToolMaterials.WOOD, EnchantmentTags.SWORD_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SWORD_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_WOODEN_TOOL), new FuelItemComponent(200)).build()));
        registerable.register(ItemKeys.WOODEN_SHOVEL, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.WOODEN_SHOVEL).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.WOOD, 1, BlockTags.SHOVEL_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.WOOD, EnchantmentTags.SHOVEL_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SHOVEL_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_WOODEN_TOOL), new FuelItemComponent(200)).build()));
        registerable.register(ItemKeys.WOODEN_PICKAXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.WOODEN_PICKAXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.WOOD, 1, BlockTags.PICKAXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.WOOD, EnchantmentTags.PICKAXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.PICKAXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_WOODEN_TOOL), new FuelItemComponent(200)).build()));
        registerable.register(ItemKeys.WOODEN_AXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.WOODEN_AXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.WOOD, 1, BlockTags.AXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.WOOD, EnchantmentTags.AXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.AXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_WOODEN_TOOL), new FuelItemComponent(200)).build()));
        registerable.register(ItemKeys.WOODEN_HOE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.WOODEN_HOE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.WOOD, 1, BlockTags.HOE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.WOOD, EnchantmentTags.HOE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.HOE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_WOODEN_TOOL), new FuelItemComponent(200)).build()));
        registerable.register(ItemKeys.STONE_SWORD, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.STONE_SWORD).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.STONE, 2)).with(new WeaponItemComponent(1), EnchantableItemComponent.enchants(ToolMaterials.STONE, EnchantmentTags.SWORD_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SWORD_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_STONE_TOOL)).build()));
        registerable.register(ItemKeys.STONE_SHOVEL, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.STONE_SHOVEL).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.STONE, 1, BlockTags.SHOVEL_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.STONE, EnchantmentTags.SHOVEL_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SHOVEL_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_STONE_TOOL)).build()));
        registerable.register(ItemKeys.STONE_PICKAXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.STONE_PICKAXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.STONE, 1, BlockTags.PICKAXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.STONE, EnchantmentTags.PICKAXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.PICKAXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_STONE_TOOL)).build()));
        registerable.register(ItemKeys.STONE_AXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.STONE_AXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.STONE, 1, BlockTags.AXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.STONE, EnchantmentTags.AXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.AXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_STONE_TOOL)).build()));
        registerable.register(ItemKeys.STONE_HOE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.STONE_HOE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.STONE, 1, BlockTags.HOE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.STONE, EnchantmentTags.HOE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.HOE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_STONE_TOOL)).build()));
        registerable.register(ItemKeys.GOLDEN_SWORD, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.GOLDEN_SWORD).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.GOLD, 2)).with(new WeaponItemComponent(1), EnchantableItemComponent.enchants(ToolMaterials.GOLD, EnchantmentTags.SWORD_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SWORD_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_GOLDEN_TOOL)).build()));
        registerable.register(ItemKeys.GOLDEN_SHOVEL, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.GOLDEN_SHOVEL).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.GOLD, 1, BlockTags.SHOVEL_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.GOLD, EnchantmentTags.SHOVEL_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SHOVEL_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_GOLDEN_TOOL)).build()));
        registerable.register(ItemKeys.GOLDEN_PICKAXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.GOLDEN_PICKAXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.GOLD, 1, BlockTags.PICKAXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.GOLD, EnchantmentTags.PICKAXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.PICKAXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_GOLDEN_TOOL)).build()));
        registerable.register(ItemKeys.GOLDEN_AXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.GOLDEN_AXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.GOLD, 1, BlockTags.AXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.GOLD, EnchantmentTags.AXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.AXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_GOLDEN_TOOL)).build()));
        registerable.register(ItemKeys.GOLDEN_HOE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.GOLDEN_HOE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.GOLD, 1, BlockTags.HOE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.GOLD, EnchantmentTags.HOE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.HOE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_GOLDEN_TOOL)).build()));
        registerable.register(ItemKeys.IRON_SWORD, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.IRON_SWORD).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.IRON, 2)).with(new WeaponItemComponent(1), EnchantableItemComponent.enchants(ToolMaterials.IRON, EnchantmentTags.SWORD_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SWORD_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_IRON_TOOL)).build()));
        registerable.register(ItemKeys.IRON_SHOVEL, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.IRON_SHOVEL).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.IRON, 1, BlockTags.SHOVEL_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.IRON, EnchantmentTags.SHOVEL_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SHOVEL_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_IRON_TOOL)).build()));
        registerable.register(ItemKeys.IRON_PICKAXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.IRON_PICKAXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.IRON, 1, BlockTags.PICKAXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.IRON, EnchantmentTags.PICKAXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.PICKAXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_IRON_TOOL)).build()));
        registerable.register(ItemKeys.IRON_AXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.IRON_AXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.IRON, 1, BlockTags.AXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.IRON, EnchantmentTags.AXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.AXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_IRON_TOOL)).build()));
        registerable.register(ItemKeys.IRON_HOE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.IRON_HOE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.IRON, 1, BlockTags.HOE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.IRON, EnchantmentTags.HOE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.HOE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_IRON_TOOL)).build()));
        registerable.register(ItemKeys.DIAMOND_SWORD, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.DIAMOND_SWORD).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.DIAMOND, 2)).with(new WeaponItemComponent(1), EnchantableItemComponent.enchants(ToolMaterials.DIAMOND, EnchantmentTags.SWORD_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SWORD_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_DIAMOND_TOOL)).build()));
        registerable.register(ItemKeys.DIAMOND_SHOVEL, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.DIAMOND_SHOVEL).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.DIAMOND, 1, BlockTags.SHOVEL_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.DIAMOND, EnchantmentTags.SHOVEL_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SHOVEL_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_DIAMOND_TOOL)).build()));
        registerable.register(ItemKeys.DIAMOND_PICKAXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.DIAMOND_PICKAXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.DIAMOND, 1, BlockTags.PICKAXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.DIAMOND, EnchantmentTags.PICKAXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.PICKAXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_DIAMOND_TOOL)).build()));
        registerable.register(ItemKeys.DIAMOND_AXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.DIAMOND_AXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.DIAMOND, 1, BlockTags.AXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.DIAMOND, EnchantmentTags.AXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.AXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_DIAMOND_TOOL)).build()));
        registerable.register(ItemKeys.DIAMOND_HOE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.DIAMOND_HOE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.DIAMOND, 1, BlockTags.HOE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.DIAMOND, EnchantmentTags.HOE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.HOE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_DIAMOND_TOOL)).build()));
        registerable.register(ItemKeys.NETHERITE_SWORD, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.NETHERITE_SWORD).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.NETHERITE, 2)).with(new WeaponItemComponent(1), EnchantableItemComponent.enchants(ToolMaterials.NETHERITE, EnchantmentTags.SWORD_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SWORD_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_NETHERITE_TOOL)).build()));
        registerable.register(ItemKeys.NETHERITE_SHOVEL, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.NETHERITE_SHOVEL).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.NETHERITE, 1, BlockTags.SHOVEL_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.NETHERITE, EnchantmentTags.SHOVEL_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.SHOVEL_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_NETHERITE_TOOL)).build()));
        registerable.register(ItemKeys.NETHERITE_PICKAXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.NETHERITE_PICKAXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.NETHERITE, 1, BlockTags.PICKAXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.NETHERITE, EnchantmentTags.PICKAXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.PICKAXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_NETHERITE_TOOL)).build()));
        registerable.register(ItemKeys.NETHERITE_AXE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.NETHERITE_AXE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.NETHERITE, 1, BlockTags.AXE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.NETHERITE, EnchantmentTags.AXE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.AXE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_NETHERITE_TOOL)).build()));
        registerable.register(ItemKeys.NETHERITE_HOE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.NETHERITE_HOE).build(), 1), ItemComponentSet.builder().with(ToolItemComponent.from(ToolMaterials.NETHERITE, 1, BlockTags.HOE_MINEABLE)).with(new WeaponItemComponent(2), EnchantableItemComponent.enchants(ToolMaterials.NETHERITE, EnchantmentTags.HOE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.HOE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_NETHERITE_TOOL)).build()));
        registerable.register(ItemKeys.MUSHROOM_STEW, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.MUSHROOM_STEW).build(), 1), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.MUSHROOM_STEW)).build()));
        registerable.register(ItemKeys.FEATHER, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.FEATHER).build(), 64), ItemComponentSet.builder().with(new TestItemComponent(true)).build()));
        registerable.register(ItemKeys.BREAD, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.BREAD).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.BREAD)).with(new CompostableItemComponent(0.85f)).build()));
        registerable.register(ItemKeys.IRON_HELMET, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.IRON_HELMET).build(), 1), ItemComponentSet.builder().with(ArmorItemComponent.from(net.minecraft.item.ArmorMaterials.IRON, ArmorItem.Type.HELMET, armorMaterials.getOrThrow(ArmorMaterialKeys.IRON))).with(EnchantableItemComponent.enchants(net.minecraft.item.ArmorMaterials.IRON, EnchantmentTags.HELMET_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.HELMET_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_IRON_ARMOR)).build()));
        registerable.register(ItemKeys.IRON_CHESTPLATE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.IRON_CHESTPLATE).build(), 1), ItemComponentSet.builder().with(ArmorItemComponent.from(net.minecraft.item.ArmorMaterials.IRON, ArmorItem.Type.CHESTPLATE, armorMaterials.getOrThrow(ArmorMaterialKeys.IRON))).with(EnchantableItemComponent.enchants(net.minecraft.item.ArmorMaterials.IRON, EnchantmentTags.CHESTPLATE_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.CHESTPLATE_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_IRON_ARMOR)).build()));
        registerable.register(ItemKeys.IRON_LEGGINGS, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.IRON_LEGGINGS).build(), 1), ItemComponentSet.builder().with(ArmorItemComponent.from(net.minecraft.item.ArmorMaterials.IRON, ArmorItem.Type.LEGGINGS, armorMaterials.getOrThrow(ArmorMaterialKeys.IRON))).with(EnchantableItemComponent.enchants(net.minecraft.item.ArmorMaterials.IRON, EnchantmentTags.LEGGINGS_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.LEGGINGS_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_IRON_ARMOR)).build()));
        registerable.register(ItemKeys.IRON_BOOTS, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.IRON_BOOTS).build(), 1), ItemComponentSet.builder().with(ArmorItemComponent.from(net.minecraft.item.ArmorMaterials.IRON, ArmorItem.Type.BOOTS, armorMaterials.getOrThrow(ArmorMaterialKeys.IRON))).with(EnchantableItemComponent.enchants(net.minecraft.item.ArmorMaterials.IRON, EnchantmentTags.BOOTS_ENCHANTING), ForgeableItemComponent.of(EnchantmentTags.BOOTS_FORGING), new RepairableItemComponent(ItemTagsUtil.REPAIRS_IRON_ARMOR)).build()));
        registerable.register(ItemKeys.PORKCHOP, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.PORKCHOP).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.PORKCHOP)).build()));
        registerable.register(ItemKeys.COOKED_PORKCHOP, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.COOKED_PORKCHOP).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.COOKED_PORKCHOP)).build()));
        registerable.register(ItemKeys.GOLDEN_APPLE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.GOLDEN_APPLE).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.GOLDEN_APPLE)).build()));
        registerable.register(ItemKeys.ENCHANTED_GOLDEN_APPLE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.ENCHANTED_GOLDEN_APPLE).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.ENCHANTED_GOLDEN_APPLE)).build()));
        registerable.register(ItemKeys.WATER_BUCKET, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.WATER_BUCKET).build(), 1)));
        registerable.register(ItemKeys.BOOK, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.BOOK).build(), 64), ItemComponentSet.builder().with(EnchantableItemComponent.transforms(1, items.getOrThrow(ItemKeys.ENCHANTED_BOOK))).build()));
        registerable.register(ItemKeys.COD, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.COD).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.COD)).build()));
        registerable.register(ItemKeys.SALMON, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.SALMON).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.SALMON)).build()));
        registerable.register(ItemKeys.TROPICAL_FISH, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.TROPICAL_FISH).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.TROPICAL_FISH)).build()));
        registerable.register(ItemKeys.PUFFERFISH, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.PUFFERFISH).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.PUFFERFISH)).build()));
        registerable.register(ItemKeys.COOKED_COD, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.COOKED_COD).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.COOKED_COD)).build()));
        registerable.register(ItemKeys.COOKED_SALMON, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.COOKED_SALMON).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.COOKED_SALMON)).build()));
        registerable.register(ItemKeys.COOKIE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.COOKIE).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.COOKIE)).with(new CompostableItemComponent(0.85f)).build()));
        registerable.register(ItemKeys.MELON_SLICE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.MELON_SLICE).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.MELON_SLICE)).with(new CompostableItemComponent(0.5f)).build()));
        registerable.register(ItemKeys.DRIED_KELP, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.DRIED_KELP).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.DRIED_KELP)).with(new CompostableItemComponent(0.3f)).build()));
        registerable.register(ItemKeys.BEEF, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.BEEF).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.BEEF)).build()));
        registerable.register(ItemKeys.COOKED_BEEF, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.COOKED_BEEF).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.COOKED_BEEF)).build()));
        registerable.register(ItemKeys.CHICKEN, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.CHICKEN).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.CHICKEN)).build()));
        registerable.register(ItemKeys.COOKED_CHICKEN, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.COOKED_CHICKEN).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.COOKED_CHICKEN)).build()));
        registerable.register(ItemKeys.ROTTEN_FLESH, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.ROTTEN_FLESH).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.ROTTEN_FLESH)).build()));
        registerable.register(ItemKeys.SPIDER_EYE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.SPIDER_EYE).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.SPIDER_EYE)).build()));
        registerable.register(ItemKeys.PIG_SPAWN_EGG, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.PIG_SPAWN_EGG).build(), 64), ItemComponentSet.builder().with(new EntityItemComponent(EntityType.PIG)).build()));
        registerable.register(ItemKeys.CARROT, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.CARROT).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.CARROT)).with(new BlockItemComponent(Blocks.CARROTS), new CompostableItemComponent(0.65f)).build()));
        registerable.register(ItemKeys.POTATO, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.POTATO).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.POTATO)).with(new BlockItemComponent(Blocks.POTATOES), new CompostableItemComponent(0.65f)).build()));
        registerable.register(ItemKeys.BAKED_POTATO, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.BAKED_POTATO).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.BAKED_POTATO)).with(new CompostableItemComponent(0.85f)).build()));
        registerable.register(ItemKeys.POISONOUS_POTATO, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.POISONOUS_POTATO).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.POISONOUS_POTATO)).build()));
        registerable.register(ItemKeys.GOLDEN_CARROT, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.GOLDEN_CARROT).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.GOLDEN_CARROT)).build()));
        registerable.register(ItemKeys.PUMPKIN_PIE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.PUMPKIN_PIE).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.PUMPKIN_PIE)).with(new CompostableItemComponent(1.0f)).build()));
        registerable.register(ItemKeys.ENCHANTED_BOOK, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.ENCHANTED_BOOK).build(), 1), ItemComponentSet.builder().with(new EnchantmentHolderItemComponent(EnchantedBookItem.STORED_ENCHANTMENTS_KEY), new FoilItemComponent(true)).build()));
        registerable.register(ItemKeys.RABBIT, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.RABBIT).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.RABBIT_STEW)).build()));
        registerable.register(ItemKeys.COOKED_RABBIT, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.COOKED_RABBIT).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.COOKED_RABBIT)).build()));
        registerable.register(ItemKeys.RABBIT_STEW, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.RABBIT_STEW).build(), 1), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.RABBIT_STEW)).build()));
        registerable.register(ItemKeys.MUTTON, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.MUTTON).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.MUTTON)).build()));
        registerable.register(ItemKeys.COOKED_MUTTON, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.COOKED_MUTTON).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.COOKED_MUTTON)).build()));
        registerable.register(ItemKeys.CHORUS_FRUIT, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.CHORUS_FRUIT).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.CHORUS_FRUIT)).build()));
        registerable.register(ItemKeys.BEETROOT, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.BEETROOT).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.BEETROOT)).with(new CompostableItemComponent(0.65f)).build()));
        registerable.register(ItemKeys.BEETROOT_SOUP, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.BEETROOT_SOUP).build(), 1), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.BEETROOT_SOUP)).build()));
        registerable.register(ItemKeys.SHIELD, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.SHIELD).build(), 1), ItemComponentSet.builder().with(new EquipmentItemComponent(EquipmentSlot.OFFHAND, false), new RepairableItemComponent(ItemTagsUtil.REPAIRS_SHIELD)).build()));
        registerable.register(ItemKeys.SUSPICIOUS_STEW, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.SUSPICIOUS_STEW).build(), 1), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.SUSPICIOUS_STEW)).build()));
        registerable.register(ItemKeys.SWEET_BERRIES, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.SWEET_BERRIES).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.SWEET_BERRIES)).with(new BlockItemComponent(Blocks.SWEET_BERRY_BUSH), new CompostableItemComponent(0.3f)).build()));
        registerable.register(ItemKeys.GLOW_BERRIES, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.GLOW_BERRIES).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.GLOW_BERRIES)).with(new BlockItemComponent(Blocks.CAVE_VINES), new CompostableItemComponent(0.3f)).build()));
        registerable.register(ItemKeys.HONEY_BOTTLE, create(new ItemBase(ItemBaseDisplay.Builder.forItem(ItemKeys.HONEY_BOTTLE).build(), 64), ItemComponentSet.builder().with(FoodItemComponent.from(FoodComponents.HONEY_BOTTLE, 40)).build()));
    }

    public static RegistryKey<Item> keyFromBlock(Block block) {
        Identifier id = Registries.BLOCK.getId(block);
        return RegistryKey.of(RegistryKeys.ITEM, id);
    }

    private static Item create(ItemBase base) {
        return create(base, new ItemComponentSet());
    }

    private static Item create(ItemBase base, ItemComponentSet components) {
        Item item = new Item(new Item.Settings());
        item.setItemBase(base);
        item.setComponents(components);
        return item;
    }
}
