plugins {
	id "net.fabricmc.fabric-loom" version "${loom_version}"
	id "maven-publish"
}

version = project.mod_version
group = project.maven_group

repositories {
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

loom {
	splitEnvironmentSourceSets()
}

sourceSets {
	main {
		resources {
			srcDirs += [
				'src/main/generated'
			]
		}
	}
	datagen {
		compileClasspath += client.compileClasspath
		runtimeClasspath += client.runtimeClasspath
		compileClasspath += client.output
		runtimeClasspath += client.output
	}
	gametest {
		compileClasspath += client.compileClasspath
		runtimeClasspath += client.runtimeClasspath
		compileClasspath += client.output
		runtimeClasspath += client.output
	}
}

apply from: 'gradle/package-info.gradle'

loom {
	mods {
		itematic {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
		"itematic-datagen" {
			sourceSet sourceSets.datagen
		}
		"itematic-gametest" {
			sourceSet sourceSets.gametest
		}
	}

	runs {
		datagenClient {
			inherit client
			name "Data Generation"
			vmArg "-Dfabric-api.datagen"
			vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"
			vmArg "-Dfabric-api.datagen.modid=itematic-datagen"

			runDir "build/datagen"
			source sourceSets.datagen
		}
		gametest {
			inherit server
			name "GameTest"
			vmArg "-Dfabric-api.gametest"
			vmArg "-Dfabric-api.gametest.report-file=${project.layout.buildDirectory.file("junit.xml").get()}"

			runDir "build/gametest"
			source sourceSets.gametest
		}
		gametestClient {
			inherit client
			name "GameTest Client"
			vmArg "-Ditematic.gametest.structure-output-directory=${file("src/gametest/resources/data")}"

			runDir "run"
			source sourceSets.gametest
		}
	}
	accessWidenerPath = file("src/main/resources/itematic.classtweaker")
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}_${archives_base_name}"}
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
