package net.errorcraft.itematic.world.item.group.entry;

import net.errorcraft.itematic.core.registries.ItematicRegistries;
import net.errorcraft.itematic.references.ItemIds;
import net.errorcraft.itematic.tags.ItemGroupItemTags;
import net.errorcraft.itematic.world.item.group.entry.entries.EnchantmentItemGroupEntry;
import net.errorcraft.itematic.world.item.group.entry.entries.InstrumentItemGroupEntry;
import net.errorcraft.itematic.world.item.group.entry.entries.PaintingVariantItemGroupEntry;
import net.errorcraft.itematic.world.item.group.entry.entries.PotionItemGroupEntry;
import net.errorcraft.itematic.world.item.group.entry.entries.SuspiciousEffectIngredientItemGroupEntry;
import net.minecraft.core.HolderGetter;
import net.minecraft.core.component.DataComponentPatch;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.InstrumentTags;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.PaintingVariantTags;
import net.minecraft.world.entity.raid.Raid;
import net.minecraft.world.item.FireworkRocketItem;
import net.minecraft.world.item.Instrument;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.component.BlockItemStateProperties;
import net.minecraft.world.item.component.Fireworks;
import net.minecraft.world.item.component.OminousBottleAmplifier;
import net.minecraft.world.level.block.LightBlock;
import net.minecraft.world.level.block.TestBlock;
import net.minecraft.world.level.block.entity.BannerPattern;
import net.minecraft.world.level.block.state.properties.TestBlockMode;

import java.util.List;

public class ItemGroupEntryProviders {
    public static final ResourceKey<ItemGroupEntryProvider> BUILDING_BLOCKS = of("building_blocks");
    public static final ResourceKey<ItemGroupEntryProvider> COLORED_BLOCKS = of("colored_blocks");
    public static final ResourceKey<ItemGroupEntryProvider> NATURAL_BLOCKS = of("natural_blocks");
    public static final ResourceKey<ItemGroupEntryProvider> FUNCTIONAL_BLOCKS = of("functional_blocks");
    public static final ResourceKey<ItemGroupEntryProvider> REDSTONE_BLOCKS = of("redstone_blocks");
    public static final ResourceKey<ItemGroupEntryProvider> TOOLS_AND_UTILITIES = of("tools_and_utilities");
    public static final ResourceKey<ItemGroupEntryProvider> COMBAT = of("combat");
    public static final ResourceKey<ItemGroupEntryProvider> FOOD_AND_DRINKS = of("food_and_drinks");
    public static final ResourceKey<ItemGroupEntryProvider> INGREDIENTS = of("ingredients");
    public static final ResourceKey<ItemGroupEntryProvider> SPAWN_EGGS = of("spawn_eggs");
    public static final ResourceKey<ItemGroupEntryProvider> OP_BLOCKS = of("op_blocks");

    private ItemGroupEntryProviders() {}

    public static void bootstrap(BootstrapContext<ItemGroupEntryProvider> registerable) {
        HolderGetter<Item> items = registerable.lookup(Registries.ITEM);
        HolderGetter<BannerPattern> bannerPatterns = registerable.lookup(Registries.BANNER_PATTERN);
        HolderGetter<Instrument> instruments = registerable.lookup(Registries.INSTRUMENT);

        registerable.register(BUILDING_BLOCKS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.WOODEN_BUILDING_BLOCKS)
            .add(ItemGroupItemTags.STONE_LIKE_BUILDING_BLOCKS)
            .add(ItemIds.COAL_BLOCK)
            .add(ItemGroupItemTags.IRON_BUILDING_BLOCKS)
            .add(ItemGroupItemTags.GOLD_BUILDING_BLOCKS)
            .add(ItemIds.REDSTONE_BLOCK)
            .add(ItemIds.EMERALD_BLOCK)
            .add(ItemIds.LAPIS_BLOCK)
            .add(ItemIds.DIAMOND_BLOCK)
            .add(ItemIds.NETHERITE_BLOCK)
            .add(ItemGroupItemTags.QUARTZ_BUILDING_BLOCKS)
            .add(ItemGroupItemTags.SMOOTH_QUARTZ_BUILDING_BLOCKS)
            .add(ItemIds.AMETHYST_BLOCK)
            .add(ItemGroupItemTags.COPPER_LIKE_BUILDING_BLOCKS)
            .build()
        );
        registerable.register(COLORED_BLOCKS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.WOOL)
            .add(ItemGroupItemTags.WOOL_CARPETS)
            .add(ItemGroupItemTags.TERRACOTTA)
            .add(ItemGroupItemTags.CONCRETE)
            .add(ItemGroupItemTags.CONCRETE_POWDER)
            .add(ItemGroupItemTags.GLAZED_TERRACOTTA)
            .add(ItemGroupItemTags.GLASS)
            .add(ItemGroupItemTags.GLASS_PANES)
            .add(ItemGroupItemTags.SHULKER_BOXES)
            .add(ItemGroupItemTags.BEDS)
            .add(ItemGroupItemTags.CANDLES)
            .add(ItemGroupItemTags.BANNERS)
            .build()
        );
        registerable.register(NATURAL_BLOCKS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.GRASS_LIKE_BLOCKS)
            .add(ItemGroupItemTags.DIRT_LIKE_BLOCKS)
            .add(ItemIds.GRAVEL)
            .add(ItemGroupItemTags.SAND_BLOCKS)
            .add(ItemGroupItemTags.ICE_BLOCKS)
            .add(ItemGroupItemTags.SNOW_BLOCKS)
            .add(ItemGroupItemTags.MOSS_BLOCKS)
            .add(ItemGroupItemTags.STONE_LIKE_BLOCKS)
            .add(ItemGroupItemTags.NETHER_BLOCKS)
            .add(ItemIds.END_STONE)
            .add(ItemGroupItemTags.ORE_LIKE_BLOCKS)
            .add(ItemIds.GLOWSTONE)
            .add(ItemGroupItemTags.AMETHYST_BLOCKS)
            .add(ItemGroupItemTags.LOG_LIKE_BLOCKS)
            .add(ItemGroupItemTags.LEAVES)
            .add(ItemGroupItemTags.MUSHROOM_LIKE_BLOCKS)
            .add(ItemGroupItemTags.SAPLINGS)
            .add(ItemGroupItemTags.PLANTS)
            .add(ItemGroupItemTags.EGG_LIKE_BLOCKS)
            .add(ItemIds.DRIED_GHAST)
            .add(ItemGroupItemTags.SEEDS)
            .add(ItemGroupItemTags.WATER_BLOCKS)
            .add(ItemIds.SPONGE)
            .add(ItemIds.WET_SPONGE)
            .add(ItemIds.MELON)
            .add(ItemGroupItemTags.PUMPKINS)
            .add(ItemIds.HAY_BLOCK)
            .add(ItemIds.BEE_NEST)
            .add(ItemIds.HONEYCOMB_BLOCK)
            .add(ItemIds.SLIME_BLOCK)
            .add(ItemIds.HONEY_BLOCK)
            .add(ItemIds.RESIN_BLOCK)
            .add(ItemGroupItemTags.FROGLIGHTS)
            .add(ItemGroupItemTags.SCULK)
            .add(ItemIds.COBWEB)
            .add(ItemIds.BEDROCK)
            .build()
        );
        registerable.register(FUNCTIONAL_BLOCKS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.TORCHES)
            .add(ItemGroupItemTags.LANTERNS)
            .add(ItemGroupItemTags.CHAINS)
            .add(ItemGroupItemTags.LIGHT_EMITTING_BLOCKS)
            .add(ItemIds.CRAFTING_TABLE)
            .add(ItemIds.STONECUTTER)
            .add(ItemIds.CARTOGRAPHY_TABLE)
            .add(ItemIds.FLETCHING_TABLE)
            .add(ItemIds.SMITHING_TABLE)
            .add(ItemIds.GRINDSTONE)
            .add(ItemIds.LOOM)
            .add(ItemIds.FURNACE)
            .add(ItemIds.SMOKER)
            .add(ItemIds.BLAST_FURNACE)
            .add(ItemIds.CAMPFIRE)
            .add(ItemIds.SOUL_CAMPFIRE)
            .add(ItemIds.ANVIL)
            .add(ItemIds.CHIPPED_ANVIL)
            .add(ItemIds.DAMAGED_ANVIL)
            .add(ItemIds.COMPOSTER)
            .add(ItemIds.NOTE_BLOCK)
            .add(ItemIds.JUKEBOX)
            .add(ItemIds.ENCHANTING_TABLE)
            .add(ItemIds.END_CRYSTAL)
            .add(ItemIds.BREWING_STAND)
            .add(ItemIds.CAULDRON)
            .add(ItemIds.BELL)
            .add(ItemIds.BEACON)
            .add(ItemIds.CONDUIT)
            .add(ItemIds.LODESTONE)
            .add(ItemIds.LADDER)
            .add(ItemIds.SCAFFOLDING)
            .add(ItemIds.BEE_NEST)
            .add(ItemIds.BEEHIVE)
            .add(ItemIds.SUSPICIOUS_SAND)
            .add(ItemIds.SUSPICIOUS_GRAVEL)
            .add(ItemGroupItemTags.LIGHTNING_RODS)
            .add(ItemIds.FLOWER_POT)
            .add(ItemIds.DECORATED_POT)
            .add(ItemIds.ARMOR_STAND)
            .add(ItemIds.ITEM_FRAME)
            .add(ItemIds.GLOW_ITEM_FRAME)
            .add(ItemIds.PAINTING)
            .add(PaintingVariantItemGroupEntry.expected(items.getOrThrow(ItemIds.PAINTING), PaintingVariantTags.PLACEABLE))
            .add(ItemIds.BOOKSHELF)
            .add(ItemIds.CHISELED_BOOKSHELF)
            .add(ItemGroupItemTags.SHELVES)
            .add(ItemIds.LECTERN)
            .add(ItemIds.TINTED_GLASS)
            .add(ItemGroupItemTags.SIGNS)
            .add(ItemIds.CHEST)
            .add(ItemIds.BARREL)
            .add(ItemIds.ENDER_CHEST)
            .add(ItemGroupItemTags.SHULKER_BOXES)
            .add(ItemIds.RESPAWN_ANCHOR)
            .add(ItemGroupItemTags.BEDS)
            .add(ItemGroupItemTags.CANDLES)
            .add(ItemGroupItemTags.BANNERS)
            .add(ItemIds.WHITE_BANNER, Raid.getBannerComponentPatch(bannerPatterns))
            .add(ItemGroupItemTags.HEADS)
            .add(ItemIds.DRAGON_EGG)
            .add(ItemIds.END_PORTAL_FRAME)
            .add(ItemIds.ENDER_EYE)
            .add(ItemIds.VAULT)
            .add(ItemGroupItemTags.COPPER_GOLEMS)
            .add(ItemGroupItemTags.INFESTED_BLOCKS)
            .build()
        );
        registerable.register(REDSTONE_BLOCKS, ItemGroupEntryProvider.builder(items)
            .add(ItemIds.REDSTONE)
            .add(ItemIds.REDSTONE_TORCH)
            .add(ItemIds.REDSTONE_BLOCK)
            .add(ItemIds.REPEATER)
            .add(ItemIds.COMPARATOR)
            .add(ItemIds.TARGET)
            .add(ItemIds.COPPER_BULB)
            .add(ItemIds.EXPOSED_COPPER_BULB)
            .add(ItemIds.WEATHERED_COPPER_BULB)
            .add(ItemIds.OXIDIZED_COPPER_BULB)
            .add(ItemIds.LEVER)
            .add(ItemIds.OAK_BUTTON)
            .add(ItemIds.STONE_BUTTON)
            .add(ItemIds.OAK_PRESSURE_PLATE)
            .add(ItemIds.STONE_PRESSURE_PLATE)
            .add(ItemIds.LIGHT_WEIGHTED_PRESSURE_PLATE)
            .add(ItemIds.HEAVY_WEIGHTED_PRESSURE_PLATE)
            .add(ItemIds.SCULK_SENSOR)
            .add(ItemIds.CALIBRATED_SCULK_SENSOR)
            .add(ItemIds.SCULK_SHRIEKER)
            .add(ItemIds.AMETHYST_BLOCK)
            .add(ItemIds.WHITE_WOOL)
            .add(ItemIds.TRIPWIRE_HOOK)
            .add(ItemIds.STRING)
            .add(ItemIds.LECTERN)
            .add(ItemIds.DAYLIGHT_DETECTOR)
            .add(ItemGroupItemTags.LIGHTNING_RODS)
            .add(ItemIds.PISTON)
            .add(ItemIds.STICKY_PISTON)
            .add(ItemIds.SLIME_BLOCK)
            .add(ItemIds.HONEY_BLOCK)
            .add(ItemIds.DISPENSER)
            .add(ItemIds.DROPPER)
            .add(ItemIds.CRAFTER)
            .add(ItemIds.HOPPER)
            .add(ItemGroupItemTags.CHESTS)
            .add(ItemIds.BARREL)
            .add(ItemIds.CHISELED_BOOKSHELF)
            .add(ItemGroupItemTags.SHELVES)
            .add(ItemIds.FURNACE)
            .add(ItemIds.TRAPPED_CHEST)
            .add(ItemIds.JUKEBOX)
            .add(ItemIds.DECORATED_POT)
            .add(ItemIds.OBSERVER)
            .add(ItemIds.NOTE_BLOCK)
            .add(ItemIds.COMPOSTER)
            .add(ItemIds.CAULDRON)
            .add(ItemGroupItemTags.RAILS)
            .add(ItemGroupItemTags.MINECARTS)
            .add(ItemIds.OAK_CHEST_BOAT)
            .add(ItemIds.BAMBOO_CHEST_RAFT)
            .add(ItemIds.OAK_DOOR)
            .add(ItemIds.IRON_DOOR)
            .add(ItemIds.OAK_FENCE_GATE)
            .add(ItemIds.OAK_TRAPDOOR)
            .add(ItemIds.IRON_TRAPDOOR)
            .add(ItemIds.TNT)
            .add(ItemIds.REDSTONE_LAMP)
            .add(ItemIds.BELL)
            .add(ItemIds.BIG_DRIPLEAF)
            .add(ItemIds.ARMOR_STAND)
            .add(ItemIds.REDSTONE_ORE)
            .build()
        );
        registerable.register(TOOLS_AND_UTILITIES, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.TOOLS)
            .add(ItemGroupItemTags.BUCKETS)
            .add(ItemIds.FISHING_ROD)
            .add(ItemIds.FLINT_AND_STEEL)
            .add(ItemIds.FIRE_CHARGE)
            .add(ItemIds.BONE_MEAL)
            .add(ItemIds.SHEARS)
            .add(ItemIds.BRUSH)
            .add(ItemIds.NAME_TAG)
            .add(ItemIds.LEAD)
            .add(ItemGroupItemTags.BUNDLES)
            .add(ItemIds.COMPASS)
            .add(ItemIds.RECOVERY_COMPASS)
            .add(ItemIds.CLOCK)
            .add(ItemIds.SPYGLASS)
            .add(ItemIds.MAP)
            .add(ItemIds.WRITABLE_BOOK)
            .add(ItemIds.WIND_CHARGE)
            .add(ItemIds.ENDER_PEARL)
            .add(ItemIds.ENDER_EYE)
            .add(ItemIds.ELYTRA)
            .add(ItemGroupEntryProviders::flightDuration)
            .add(ItemIds.SADDLE)
            .add(ItemGroupItemTags.HARNESSES)
            .add(ItemIds.CARROT_ON_A_STICK)
            .add(ItemIds.WARPED_FUNGUS_ON_A_STICK)
            .add(ItemGroupItemTags.BOATS)
            .add(ItemGroupItemTags.RAILS)
            .add(ItemGroupItemTags.MINECARTS)
            .add(InstrumentItemGroupEntry.of(items.getOrThrow(ItemIds.GOAT_HORN), instruments.getOrThrow(InstrumentTags.GOAT_HORNS)))
            .add(ItemGroupItemTags.MUSIC_DISCS)
            .build()
        );
        registerable.register(COMBAT, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.SWORDS)
            .add(ItemGroupItemTags.SPEARS)
            .add(ItemGroupItemTags.AXES)
            .add(ItemIds.TRIDENT)
            .add(ItemIds.MACE)
            .add(ItemIds.SHIELD)
            .add(ItemGroupItemTags.ARMOR)
            .add(ItemGroupItemTags.HORSE_ARMOR)
            .add(ItemIds.WOLF_ARMOR)
            .add(ItemGroupItemTags.NAUTILUS_ARMOR)
            .add(ItemIds.TOTEM_OF_UNDYING)
            .add(ItemIds.TNT)
            .add(ItemIds.END_CRYSTAL)
            .add(ItemIds.SNOWBALL)
            .add(ItemGroupItemTags.EGGS)
            .add(ItemIds.WIND_CHARGE)
            .add(ItemIds.BOW)
            .add(ItemIds.CROSSBOW)
            .add(ItemGroupEntryProviders::flightDuration)
            .add(ItemIds.ARROW)
            .add(ItemIds.SPECTRAL_ARROW)
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemIds.TIPPED_ARROW)))
            .build()
        );
        registerable.register(FOOD_AND_DRINKS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.FOOD)
            .add(SuspiciousEffectIngredientItemGroupEntry.of(items.getOrThrow(ItemIds.SUSPICIOUS_STEW)))
            .add(ItemIds.MILK_BUCKET)
            .add(ItemIds.HONEY_BOTTLE)
            .add(ItemGroupEntryProviders::ominousBottles)
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemIds.POTION)))
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemIds.SPLASH_POTION)))
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemIds.LINGERING_POTION)))
            .build()
        );
        registerable.register(INGREDIENTS, ItemGroupEntryProvider.builder(items)
            .add(ItemIds.COAL)
            .add(ItemIds.CHARCOAL)
            .add(ItemIds.RAW_IRON)
            .add(ItemIds.RAW_COPPER)
            .add(ItemIds.RAW_GOLD)
            .add(ItemIds.EMERALD)
            .add(ItemIds.LAPIS_LAZULI)
            .add(ItemIds.DIAMOND)
            .add(ItemIds.ANCIENT_DEBRIS)
            .add(ItemIds.QUARTZ)
            .add(ItemIds.AMETHYST_SHARD)
            .add(ItemIds.RESIN_CLUMP)
            .add(ItemGroupItemTags.NUGGETS)
            .add(ItemIds.IRON_INGOT)
            .add(ItemIds.COPPER_INGOT)
            .add(ItemIds.GOLD_INGOT)
            .add(ItemIds.NETHERITE_SCRAP)
            .add(ItemIds.NETHERITE_INGOT)
            .add(ItemIds.STICK)
            .add(ItemIds.FLINT)
            .add(ItemIds.WHEAT)
            .add(ItemIds.BONE)
            .add(ItemIds.BONE_MEAL)
            .add(ItemIds.STRING)
            .add(ItemIds.FEATHER)
            .add(ItemIds.SNOWBALL)
            .add(ItemGroupItemTags.EGGS)
            .add(ItemIds.LEATHER)
            .add(ItemIds.RABBIT_HIDE)
            .add(ItemIds.HONEYCOMB)
            .add(ItemIds.INK_SAC)
            .add(ItemIds.GLOW_INK_SAC)
            .add(ItemIds.TURTLE_SCUTE)
            .add(ItemIds.ARMADILLO_SCUTE)
            .add(ItemIds.SLIME_BALL)
            .add(ItemIds.CLAY_BALL)
            .add(ItemIds.PRISMARINE_SHARD)
            .add(ItemIds.PRISMARINE_CRYSTALS)
            .add(ItemIds.NAUTILUS_SHELL)
            .add(ItemIds.HEART_OF_THE_SEA)
            .add(ItemIds.FIRE_CHARGE)
            .add(ItemIds.BLAZE_ROD)
            .add(ItemIds.BREEZE_ROD)
            .add(ItemIds.HEAVY_CORE)
            .add(ItemIds.NETHER_STAR)
            .add(ItemIds.ENDER_PEARL)
            .add(ItemIds.ENDER_EYE)
            .add(ItemIds.SHULKER_SHELL)
            .add(ItemIds.POPPED_CHORUS_FRUIT)
            .add(ItemIds.ECHO_SHARD)
            .add(ItemIds.DISC_FRAGMENT_5)
            .add(ItemGroupItemTags.DYES)
            .add(ItemIds.BOWL)
            .add(ItemIds.BRICK)
            .add(ItemIds.NETHER_BRICK)
            .add(ItemIds.RESIN_BRICK)
            .add(ItemIds.PAPER)
            .add(ItemIds.BOOK)
            .add(ItemIds.FIREWORK_STAR)
            .add(ItemGroupItemTags.BREWING_INGREDIENTS)
            .add(ItemGroupItemTags.BANNER_PATTERNS)
            .add(ItemTags.DECORATED_POT_SHERDS)
            .add(ItemGroupItemTags.SMITHING_TEMPLATES)
            .add(ItemIds.EXPERIENCE_BOTTLE)
            .add(ItemIds.TRIAL_KEY)
            .add(ItemIds.OMINOUS_TRIAL_KEY)
            .add(EnchantmentItemGroupEntry.of(items.getOrThrow(ItemIds.ENCHANTED_BOOK)))
            .build()
        );
        registerable.register(SPAWN_EGGS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.SPAWNERS)
            .add(ItemIds.CREAKING_HEART)
            .add(ItemIds.ALLAY_SPAWN_EGG)
            .add(ItemIds.ARMADILLO_SPAWN_EGG)
            .add(ItemIds.AXOLOTL_SPAWN_EGG)
            .add(ItemIds.BAT_SPAWN_EGG)
            .add(ItemIds.BEE_SPAWN_EGG)
            .add(ItemIds.BLAZE_SPAWN_EGG)
            .add(ItemIds.BOGGED_SPAWN_EGG)
            .add(ItemIds.BREEZE_SPAWN_EGG)
            .add(ItemIds.CAMEL_SPAWN_EGG)
            .add(ItemIds.CAMEL_HUSK_SPAWN_EGG)
            .add(ItemIds.CAT_SPAWN_EGG)
            .add(ItemIds.CAVE_SPIDER_SPAWN_EGG)
            .add(ItemIds.CHICKEN_SPAWN_EGG)
            .add(ItemIds.COD_SPAWN_EGG)
            .add(ItemIds.COPPER_GOLEM_SPAWN_EGG)
            .add(ItemIds.COW_SPAWN_EGG)
            .add(ItemIds.CREAKING_SPAWN_EGG)
            .add(ItemIds.CREEPER_SPAWN_EGG)
            .add(ItemIds.DOLPHIN_SPAWN_EGG)
            .add(ItemIds.DONKEY_SPAWN_EGG)
            .add(ItemIds.DROWNED_SPAWN_EGG)
            .add(ItemIds.ELDER_GUARDIAN_SPAWN_EGG)
            .add(ItemIds.ENDERMAN_SPAWN_EGG)
            .add(ItemIds.ENDERMITE_SPAWN_EGG)
            .add(ItemIds.EVOKER_SPAWN_EGG)
            .add(ItemIds.FOX_SPAWN_EGG)
            .add(ItemIds.FROG_SPAWN_EGG)
            .add(ItemIds.GHAST_SPAWN_EGG)
            .add(ItemIds.GLOW_SQUID_SPAWN_EGG)
            .add(ItemIds.GOAT_SPAWN_EGG)
            .add(ItemIds.GUARDIAN_SPAWN_EGG)
            .add(ItemIds.HAPPY_GHAST_SPAWN_EGG)
            .add(ItemIds.HOGLIN_SPAWN_EGG)
            .add(ItemIds.HORSE_SPAWN_EGG)
            .add(ItemIds.HUSK_SPAWN_EGG)
            .add(ItemIds.IRON_GOLEM_SPAWN_EGG)
            .add(ItemIds.LLAMA_SPAWN_EGG)
            .add(ItemIds.MAGMA_CUBE_SPAWN_EGG)
            .add(ItemIds.MOOSHROOM_SPAWN_EGG)
            .add(ItemIds.MULE_SPAWN_EGG)
            .add(ItemIds.NAUTILUS_SPAWN_EGG)
            .add(ItemIds.OCELOT_SPAWN_EGG)
            .add(ItemIds.PANDA_SPAWN_EGG)
            .add(ItemIds.PARCHED_SPAWN_EGG)
            .add(ItemIds.PARROT_SPAWN_EGG)
            .add(ItemIds.PHANTOM_SPAWN_EGG)
            .add(ItemIds.PIG_SPAWN_EGG)
            .add(ItemIds.PIGLIN_SPAWN_EGG)
            .add(ItemIds.PIGLIN_BRUTE_SPAWN_EGG)
            .add(ItemIds.PILLAGER_SPAWN_EGG)
            .add(ItemIds.POLAR_BEAR_SPAWN_EGG)
            .add(ItemIds.PUFFERFISH_SPAWN_EGG)
            .add(ItemIds.RABBIT_SPAWN_EGG)
            .add(ItemIds.RAVAGER_SPAWN_EGG)
            .add(ItemIds.SALMON_SPAWN_EGG)
            .add(ItemIds.SHEEP_SPAWN_EGG)
            .add(ItemIds.SHULKER_SPAWN_EGG)
            .add(ItemIds.SILVERFISH_SPAWN_EGG)
            .add(ItemIds.SKELETON_SPAWN_EGG)
            .add(ItemIds.SKELETON_HORSE_SPAWN_EGG)
            .add(ItemIds.SLIME_SPAWN_EGG)
            .add(ItemIds.SNIFFER_SPAWN_EGG)
            .add(ItemIds.SNOW_GOLEM_SPAWN_EGG)
            .add(ItemIds.SPIDER_SPAWN_EGG)
            .add(ItemIds.SQUID_SPAWN_EGG)
            .add(ItemIds.STRAY_SPAWN_EGG)
            .add(ItemIds.STRIDER_SPAWN_EGG)
            .add(ItemIds.TADPOLE_SPAWN_EGG)
            .add(ItemIds.TRADER_LLAMA_SPAWN_EGG)
            .add(ItemIds.TROPICAL_FISH_SPAWN_EGG)
            .add(ItemIds.TURTLE_SPAWN_EGG)
            .add(ItemIds.VEX_SPAWN_EGG)
            .add(ItemIds.VILLAGER_SPAWN_EGG)
            .add(ItemIds.VINDICATOR_SPAWN_EGG)
            .add(ItemIds.WANDERING_TRADER_SPAWN_EGG)
            .add(ItemIds.WARDEN_SPAWN_EGG)
            .add(ItemIds.WITCH_SPAWN_EGG)
            .add(ItemIds.WITHER_SKELETON_SPAWN_EGG)
            .add(ItemIds.WOLF_SPAWN_EGG)
            .add(ItemIds.ZOGLIN_SPAWN_EGG)
            .add(ItemIds.ZOMBIE_SPAWN_EGG)
            .add(ItemIds.ZOMBIE_HORSE_SPAWN_EGG)
            .add(ItemIds.ZOMBIE_NAUTILUS_SPAWN_EGG)
            .add(ItemIds.ZOMBIE_VILLAGER_SPAWN_EGG)
            .add(ItemIds.ZOMBIFIED_PIGLIN_SPAWN_EGG)
            .build()
        );
        registerable.register(OP_BLOCKS, ItemGroupEntryProvider.builder(items)
            .addRequiresPermissions(ItemIds.COMMAND_BLOCK)
            .addRequiresPermissions(ItemIds.CHAIN_COMMAND_BLOCK)
            .addRequiresPermissions(ItemIds.REPEATING_COMMAND_BLOCK)
            .addRequiresPermissions(ItemIds.COMMAND_BLOCK_MINECART)
            .addRequiresPermissions(ItemIds.JIGSAW)
            .addRequiresPermissions(ItemIds.STRUCTURE_BLOCK)
            .addRequiresPermissions(ItemIds.STRUCTURE_VOID)
            .addRequiresPermissions(ItemIds.BARRIER)
            .addRequiresPermissions(ItemIds.DEBUG_STICK)
            .addRequiresPermissions(ItemIds.TEST_INSTANCE_BLOCK)
            .add(ItemGroupEntryProviders::testBlocks)
            .add(ItemGroupEntryProviders::lightBlocks)
            .add(PaintingVariantItemGroupEntry.unexpected(items.getOrThrow(ItemIds.PAINTING), PaintingVariantTags.PLACEABLE))
            .build()
        );
    }

    private static ResourceKey<ItemGroupEntryProvider> of(String id) {
        return ResourceKey.create(ItematicRegistries.ITEM_GROUP_ENTRY_PROVIDER, Identifier.withDefaultNamespace(id));
    }

    private static void flightDuration(ItemGroupEntryProvider.Builder builder) {
        for (int flightDuration : FireworkRocketItem.CRAFTABLE_DURATIONS) {
            builder.add(
                ItemIds.FIREWORK_ROCKET,
                DataComponentPatch.builder()
                    .set(DataComponents.FIREWORKS, new Fireworks(flightDuration, List.of()))
                    .build()
            );
        }
    }

    private static void ominousBottles(ItemGroupEntryProvider.Builder builder) {
        for (int amplifier = OminousBottleAmplifier.MIN_AMPLIFIER; amplifier <= OminousBottleAmplifier.MAX_AMPLIFIER; amplifier++) {
            builder.add(
                ItemIds.OMINOUS_BOTTLE,
                DataComponentPatch.builder()
                    .set(DataComponents.OMINOUS_BOTTLE_AMPLIFIER, new OminousBottleAmplifier(amplifier))
                    .build()
            );
        }
    }

    private static void testBlocks(ItemGroupEntryProvider.Builder builder) {
        for (TestBlockMode mode : TestBlockMode.values()) {
            builder.addRequiresPermissions(
                ItemIds.TEST_BLOCK,
                DataComponentPatch.builder()
                    .set(DataComponents.BLOCK_STATE, BlockItemStateProperties.EMPTY.with(TestBlock.MODE, mode))
                    .build()
            );
        }
    }

    private static void lightBlocks(ItemGroupEntryProvider.Builder builder) {
        for (int level = LightBlock.MAX_LEVEL; level >= 0; level--) {
            builder.addRequiresPermissions(
                ItemIds.LIGHT,
                DataComponentPatch.builder()
                    .set(DataComponents.BLOCK_STATE, BlockItemStateProperties.EMPTY.with(LightBlock.LEVEL, level))
                    .build()
            );
        }
    }
}
