package net.errorcraft.itematic.world.item.group.entry;

import net.errorcraft.itematic.core.registries.ItematicRegistries;
import net.errorcraft.itematic.tags.ItemGroupItemTags;
import net.errorcraft.itematic.world.item.group.entry.entries.EnchantmentItemGroupEntry;
import net.errorcraft.itematic.world.item.group.entry.entries.InstrumentItemGroupEntry;
import net.errorcraft.itematic.world.item.group.entry.entries.PaintingVariantItemGroupEntry;
import net.errorcraft.itematic.world.item.group.entry.entries.PotionItemGroupEntry;
import net.errorcraft.itematic.world.item.group.entry.entries.SuspiciousEffectIngredientItemGroupEntry;
import net.minecraft.core.HolderGetter;
import net.minecraft.core.component.DataComponentPatch;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.references.BlockItemIds;
import net.minecraft.references.ItemIds;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.InstrumentTags;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.PaintingVariantTags;
import net.minecraft.world.entity.raid.Raid;
import net.minecraft.world.item.FireworkRocketItem;
import net.minecraft.world.item.Instrument;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.component.BlockItemStateProperties;
import net.minecraft.world.item.component.Fireworks;
import net.minecraft.world.item.component.OminousBottleAmplifier;
import net.minecraft.world.level.block.LightBlock;
import net.minecraft.world.level.block.TestBlock;
import net.minecraft.world.level.block.entity.BannerPattern;
import net.minecraft.world.level.block.state.properties.TestBlockMode;

import java.util.List;

public class ItemGroupEntryProviders {
    public static final ResourceKey<ItemGroupEntryProvider> BUILDING_BLOCKS = of("building_blocks");
    public static final ResourceKey<ItemGroupEntryProvider> COLORED_BLOCKS = of("colored_blocks");
    public static final ResourceKey<ItemGroupEntryProvider> NATURAL_BLOCKS = of("natural_blocks");
    public static final ResourceKey<ItemGroupEntryProvider> FUNCTIONAL_BLOCKS = of("functional_blocks");
    public static final ResourceKey<ItemGroupEntryProvider> REDSTONE_BLOCKS = of("redstone_blocks");
    public static final ResourceKey<ItemGroupEntryProvider> TOOLS_AND_UTILITIES = of("tools_and_utilities");
    public static final ResourceKey<ItemGroupEntryProvider> COMBAT = of("combat");
    public static final ResourceKey<ItemGroupEntryProvider> FOOD_AND_DRINKS = of("food_and_drinks");
    public static final ResourceKey<ItemGroupEntryProvider> INGREDIENTS = of("ingredients");
    public static final ResourceKey<ItemGroupEntryProvider> SPAWN_EGGS = of("spawn_eggs");
    public static final ResourceKey<ItemGroupEntryProvider> OP_BLOCKS = of("op_blocks");

    private ItemGroupEntryProviders() {}

    public static void bootstrap(BootstrapContext<ItemGroupEntryProvider> registerable) {
        HolderGetter<Item> items = registerable.lookup(Registries.ITEM);
        HolderGetter<BannerPattern> bannerPatterns = registerable.lookup(Registries.BANNER_PATTERN);
        HolderGetter<Instrument> instruments = registerable.lookup(Registries.INSTRUMENT);

        registerable.register(BUILDING_BLOCKS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.WOODEN_BUILDING_BLOCKS)
            .add(ItemGroupItemTags.STONE_LIKE_BUILDING_BLOCKS)
            .add(BlockItemIds.COAL_BLOCK.item())
            .add(ItemGroupItemTags.IRON_BUILDING_BLOCKS)
            .add(ItemGroupItemTags.GOLD_BUILDING_BLOCKS)
            .add(BlockItemIds.REDSTONE_BLOCK.item())
            .add(BlockItemIds.EMERALD_BLOCK.item())
            .add(BlockItemIds.LAPIS_BLOCK.item())
            .add(BlockItemIds.DIAMOND_BLOCK.item())
            .add(BlockItemIds.NETHERITE_BLOCK.item())
            .add(ItemGroupItemTags.QUARTZ_BUILDING_BLOCKS)
            .add(ItemGroupItemTags.SMOOTH_QUARTZ_BUILDING_BLOCKS)
            .add(BlockItemIds.AMETHYST_BLOCK.item())
            .add(ItemGroupItemTags.COPPER_LIKE_BUILDING_BLOCKS)
            .build()
        );
        registerable.register(COLORED_BLOCKS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.WOOL)
            .add(ItemGroupItemTags.WOOL_CARPETS)
            .add(ItemGroupItemTags.TERRACOTTA)
            .add(ItemGroupItemTags.CONCRETE)
            .add(ItemGroupItemTags.CONCRETE_POWDER)
            .add(ItemGroupItemTags.GLAZED_TERRACOTTA)
            .add(ItemGroupItemTags.GLASS)
            .add(ItemGroupItemTags.GLASS_PANES)
            .add(ItemGroupItemTags.SHULKER_BOXES)
            .add(ItemGroupItemTags.BEDS)
            .add(ItemGroupItemTags.CANDLES)
            .add(ItemGroupItemTags.BANNERS)
            .build()
        );
        registerable.register(NATURAL_BLOCKS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.GRASS_LIKE_BLOCKS)
            .add(ItemGroupItemTags.DIRT_LIKE_BLOCKS)
            .add(BlockItemIds.GRAVEL.item())
            .add(ItemGroupItemTags.SAND_BLOCKS)
            .add(ItemGroupItemTags.ICE_BLOCKS)
            .add(ItemGroupItemTags.SNOW_BLOCKS)
            .add(ItemGroupItemTags.MOSS_BLOCKS)
            .add(ItemGroupItemTags.STONE_LIKE_BLOCKS)
            .add(ItemGroupItemTags.NETHER_BLOCKS)
            .add(BlockItemIds.END_STONE.item())
            .add(ItemGroupItemTags.ORE_LIKE_BLOCKS)
            .add(BlockItemIds.GLOWSTONE.item())
            .add(ItemGroupItemTags.AMETHYST_BLOCKS)
            .add(ItemGroupItemTags.LOG_LIKE_BLOCKS)
            .add(ItemGroupItemTags.LEAVES)
            .add(ItemGroupItemTags.MUSHROOM_LIKE_BLOCKS)
            .add(ItemGroupItemTags.SAPLINGS)
            .add(ItemGroupItemTags.PLANTS)
            .add(ItemGroupItemTags.EGG_LIKE_BLOCKS)
            .add(BlockItemIds.DRIED_GHAST.item())
            .add(ItemGroupItemTags.SEEDS)
            .add(ItemGroupItemTags.WATER_BLOCKS)
            .add(BlockItemIds.SPONGE.item())
            .add(BlockItemIds.WET_SPONGE.item())
            .add(BlockItemIds.MELON.item())
            .add(ItemGroupItemTags.PUMPKINS)
            .add(BlockItemIds.HAY_BLOCK.item())
            .add(BlockItemIds.BEE_NEST.item())
            .add(BlockItemIds.HONEYCOMB_BLOCK.item())
            .add(BlockItemIds.SLIME_BLOCK.item())
            .add(BlockItemIds.HONEY_BLOCK.item())
            .add(BlockItemIds.RESIN_BLOCK.item())
            .add(ItemGroupItemTags.FROGLIGHTS)
            .add(ItemGroupItemTags.SCULK)
            .add(BlockItemIds.COBWEB.item())
            .add(BlockItemIds.BEDROCK.item())
            .build()
        );
        registerable.register(FUNCTIONAL_BLOCKS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.TORCHES)
            .add(ItemGroupItemTags.LANTERNS)
            .add(ItemGroupItemTags.CHAINS)
            .add(ItemGroupItemTags.LIGHT_EMITTING_BLOCKS)
            .add(BlockItemIds.CRAFTING_TABLE.item())
            .add(BlockItemIds.STONECUTTER.item())
            .add(BlockItemIds.CARTOGRAPHY_TABLE.item())
            .add(BlockItemIds.FLETCHING_TABLE.item())
            .add(BlockItemIds.SMITHING_TABLE.item())
            .add(BlockItemIds.GRINDSTONE.item())
            .add(BlockItemIds.LOOM.item())
            .add(BlockItemIds.FURNACE.item())
            .add(BlockItemIds.SMOKER.item())
            .add(BlockItemIds.BLAST_FURNACE.item())
            .add(BlockItemIds.CAMPFIRE.item())
            .add(BlockItemIds.SOUL_CAMPFIRE.item())
            .add(BlockItemIds.ANVIL.item())
            .add(BlockItemIds.CHIPPED_ANVIL.item())
            .add(BlockItemIds.DAMAGED_ANVIL.item())
            .add(BlockItemIds.COMPOSTER.item())
            .add(BlockItemIds.NOTE_BLOCK.item())
            .add(BlockItemIds.JUKEBOX.item())
            .add(BlockItemIds.ENCHANTING_TABLE.item())
            .add(ItemIds.END_CRYSTAL)
            .add(BlockItemIds.BREWING_STAND.item())
            .add(BlockItemIds.CAULDRON.item())
            .add(BlockItemIds.BELL.item())
            .add(BlockItemIds.BEACON.item())
            .add(BlockItemIds.CONDUIT.item())
            .add(BlockItemIds.LODESTONE.item())
            .add(BlockItemIds.LADDER.item())
            .add(BlockItemIds.SCAFFOLDING.item())
            .add(BlockItemIds.BEE_NEST.item())
            .add(BlockItemIds.BEEHIVE.item())
            .add(BlockItemIds.SUSPICIOUS_SAND.item())
            .add(BlockItemIds.SUSPICIOUS_GRAVEL.item())
            .add(ItemGroupItemTags.LIGHTNING_RODS)
            .add(BlockItemIds.FLOWER_POT.item())
            .add(BlockItemIds.DECORATED_POT.item())
            .add(ItemIds.ARMOR_STAND)
            .add(ItemIds.ITEM_FRAME)
            .add(ItemIds.GLOW_ITEM_FRAME)
            .add(ItemIds.PAINTING)
            .add(PaintingVariantItemGroupEntry.expected(items.getOrThrow(ItemIds.PAINTING), PaintingVariantTags.PLACEABLE))
            .add(BlockItemIds.BOOKSHELF.item())
            .add(BlockItemIds.CHISELED_BOOKSHELF.item())
            .add(ItemGroupItemTags.SHELVES)
            .add(BlockItemIds.LECTERN.item())
            .add(BlockItemIds.TINTED_GLASS.item())
            .add(ItemGroupItemTags.SIGNS)
            .add(BlockItemIds.CHEST.item())
            .add(BlockItemIds.BARREL.item())
            .add(BlockItemIds.ENDER_CHEST.item())
            .add(ItemGroupItemTags.SHULKER_BOXES)
            .add(BlockItemIds.RESPAWN_ANCHOR.item())
            .add(ItemGroupItemTags.BEDS)
            .add(ItemGroupItemTags.CANDLES)
            .add(ItemGroupItemTags.BANNERS)
            .add(BlockItemIds.BANNER.white().item(), Raid.getBannerComponentPatch(bannerPatterns))
            .add(ItemGroupItemTags.HEADS)
            .add(BlockItemIds.DRAGON_EGG.item())
            .add(BlockItemIds.END_PORTAL_FRAME.item())
            .add(ItemIds.ENDER_EYE)
            .add(BlockItemIds.VAULT.item())
            .add(ItemGroupItemTags.COPPER_GOLEMS)
            .add(ItemGroupItemTags.INFESTED_BLOCKS)
            .build()
        );
        registerable.register(REDSTONE_BLOCKS, ItemGroupEntryProvider.builder(items)
            .add(BlockItemIds.REDSTONE_DUST.item())
            .add(BlockItemIds.REDSTONE_TORCH.item())
            .add(BlockItemIds.REDSTONE_BLOCK.item())
            .add(BlockItemIds.REPEATER.item())
            .add(BlockItemIds.COMPARATOR.item())
            .add(BlockItemIds.TARGET.item())
            .add(BlockItemIds.COPPER_BULB.weathering().unaffected().item())
            .add(BlockItemIds.COPPER_BULB.weathering().exposed().item())
            .add(BlockItemIds.COPPER_BULB.weathering().weathered().item())
            .add(BlockItemIds.COPPER_BULB.weathering().oxidized().item())
            .add(BlockItemIds.LEVER.item())
            .add(BlockItemIds.OAK_BUTTON.item())
            .add(BlockItemIds.STONE_BUTTON.item())
            .add(BlockItemIds.OAK_PRESSURE_PLATE.item())
            .add(BlockItemIds.STONE_PRESSURE_PLATE.item())
            .add(BlockItemIds.LIGHT_WEIGHTED_PRESSURE_PLATE.item())
            .add(BlockItemIds.HEAVY_WEIGHTED_PRESSURE_PLATE.item())
            .add(BlockItemIds.SCULK_SENSOR.item())
            .add(BlockItemIds.CALIBRATED_SCULK_SENSOR.item())
            .add(BlockItemIds.SCULK_SHRIEKER.item())
            .add(BlockItemIds.AMETHYST_BLOCK.item())
            .add(BlockItemIds.WOOL.white().item())
            .add(BlockItemIds.TRIPWIRE_HOOK.item())
            .add(BlockItemIds.TRIPWIRE.item())
            .add(BlockItemIds.LECTERN.item())
            .add(BlockItemIds.DAYLIGHT_DETECTOR.item())
            .add(ItemGroupItemTags.LIGHTNING_RODS)
            .add(BlockItemIds.PISTON.item())
            .add(BlockItemIds.STICKY_PISTON.item())
            .add(BlockItemIds.SLIME_BLOCK.item())
            .add(BlockItemIds.HONEY_BLOCK.item())
            .add(BlockItemIds.DISPENSER.item())
            .add(BlockItemIds.DROPPER.item())
            .add(BlockItemIds.CRAFTER.item())
            .add(BlockItemIds.HOPPER.item())
            .add(ItemGroupItemTags.CHESTS)
            .add(BlockItemIds.BARREL.item())
            .add(BlockItemIds.CHISELED_BOOKSHELF.item())
            .add(ItemGroupItemTags.SHELVES)
            .add(BlockItemIds.FURNACE.item())
            .add(BlockItemIds.TRAPPED_CHEST.item())
            .add(BlockItemIds.JUKEBOX.item())
            .add(BlockItemIds.DECORATED_POT.item())
            .add(BlockItemIds.OBSERVER.item())
            .add(BlockItemIds.NOTE_BLOCK.item())
            .add(BlockItemIds.COMPOSTER.item())
            .add(BlockItemIds.CAULDRON.item())
            .add(ItemGroupItemTags.RAILS)
            .add(ItemGroupItemTags.MINECARTS)
            .add(ItemIds.OAK_CHEST_BOAT)
            .add(ItemIds.BAMBOO_CHEST_RAFT)
            .add(BlockItemIds.OAK_DOOR.item())
            .add(BlockItemIds.IRON_DOOR.item())
            .add(BlockItemIds.OAK_FENCE_GATE.item())
            .add(BlockItemIds.OAK_TRAPDOOR.item())
            .add(BlockItemIds.IRON_TRAPDOOR.item())
            .add(BlockItemIds.TNT.item())
            .add(BlockItemIds.REDSTONE_LAMP.item())
            .add(BlockItemIds.BELL.item())
            .add(BlockItemIds.BIG_DRIPLEAF.item())
            .add(ItemIds.ARMOR_STAND)
            .add(BlockItemIds.REDSTONE_ORE.item())
            .build()
        );
        registerable.register(TOOLS_AND_UTILITIES, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.TOOLS)
            .add(ItemGroupItemTags.BUCKETS)
            .add(ItemIds.FISHING_ROD)
            .add(ItemIds.FLINT_AND_STEEL)
            .add(ItemIds.FIRE_CHARGE)
            .add(ItemIds.BONE_MEAL)
            .add(ItemIds.SHEARS)
            .add(ItemIds.BRUSH)
            .add(ItemIds.NAME_TAG)
            .add(ItemIds.LEAD)
            .add(ItemGroupItemTags.BUNDLES)
            .add(ItemIds.COMPASS)
            .add(ItemIds.RECOVERY_COMPASS)
            .add(ItemIds.CLOCK)
            .add(ItemIds.SPYGLASS)
            .add(ItemIds.MAP)
            .add(ItemIds.WRITABLE_BOOK)
            .add(ItemIds.WIND_CHARGE)
            .add(ItemIds.ENDER_PEARL)
            .add(ItemIds.ENDER_EYE)
            .add(ItemIds.ELYTRA)
            .add(ItemGroupEntryProviders::flightDuration)
            .add(ItemIds.SADDLE)
            .add(ItemGroupItemTags.HARNESSES)
            .add(ItemIds.CARROT_ON_A_STICK)
            .add(ItemIds.WARPED_FUNGUS_ON_A_STICK)
            .add(ItemGroupItemTags.BOATS)
            .add(ItemGroupItemTags.RAILS)
            .add(ItemGroupItemTags.MINECARTS)
            .add(InstrumentItemGroupEntry.of(items.getOrThrow(ItemIds.GOAT_HORN), instruments.getOrThrow(InstrumentTags.GOAT_HORNS)))
            .add(ItemGroupItemTags.MUSIC_DISCS)
            .build()
        );
        registerable.register(COMBAT, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.SWORDS)
            .add(ItemGroupItemTags.SPEARS)
            .add(ItemGroupItemTags.AXES)
            .add(ItemIds.TRIDENT)
            .add(ItemIds.MACE)
            .add(ItemIds.SHIELD)
            .add(ItemGroupItemTags.ARMOR)
            .add(ItemGroupItemTags.HORSE_ARMOR)
            .add(ItemIds.WOLF_ARMOR)
            .add(ItemGroupItemTags.NAUTILUS_ARMOR)
            .add(ItemIds.TOTEM_OF_UNDYING)
            .add(BlockItemIds.TNT.item())
            .add(ItemIds.END_CRYSTAL)
            .add(ItemIds.SNOWBALL)
            .add(ItemGroupItemTags.EGGS)
            .add(ItemIds.WIND_CHARGE)
            .add(ItemIds.BOW)
            .add(ItemIds.CROSSBOW)
            .add(ItemGroupEntryProviders::flightDuration)
            .add(ItemIds.ARROW)
            .add(ItemIds.SPECTRAL_ARROW)
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemIds.TIPPED_ARROW)))
            .build()
        );
        registerable.register(FOOD_AND_DRINKS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.FOOD)
            .add(SuspiciousEffectIngredientItemGroupEntry.of(items.getOrThrow(ItemIds.SUSPICIOUS_STEW)))
            .add(ItemIds.MILK_BUCKET)
            .add(ItemIds.HONEY_BOTTLE)
            .add(ItemGroupEntryProviders::ominousBottles)
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemIds.POTION)))
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemIds.SPLASH_POTION)))
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemIds.LINGERING_POTION)))
            .build()
        );
        registerable.register(INGREDIENTS, ItemGroupEntryProvider.builder(items)
            .add(ItemIds.COAL)
            .add(ItemIds.CHARCOAL)
            .add(ItemIds.RAW_IRON)
            .add(ItemIds.RAW_COPPER)
            .add(ItemIds.RAW_GOLD)
            .add(ItemIds.EMERALD)
            .add(ItemIds.LAPIS_LAZULI)
            .add(ItemIds.DIAMOND)
            .add(BlockItemIds.ANCIENT_DEBRIS.item())
            .add(ItemIds.QUARTZ)
            .add(ItemIds.AMETHYST_SHARD)
            .add(BlockItemIds.RESIN_CLUMP.item())
            .add(ItemGroupItemTags.NUGGETS)
            .add(ItemIds.IRON_INGOT)
            .add(ItemIds.COPPER_INGOT)
            .add(ItemIds.GOLD_INGOT)
            .add(ItemIds.NETHERITE_SCRAP)
            .add(ItemIds.NETHERITE_INGOT)
            .add(ItemIds.STICK)
            .add(ItemIds.FLINT)
            .add(ItemIds.WHEAT)
            .add(ItemIds.BONE)
            .add(ItemIds.BONE_MEAL)
            .add(BlockItemIds.TRIPWIRE.item())
            .add(ItemIds.FEATHER)
            .add(ItemIds.SNOWBALL)
            .add(ItemGroupItemTags.EGGS)
            .add(ItemIds.LEATHER)
            .add(ItemIds.RABBIT_HIDE)
            .add(ItemIds.HONEYCOMB)
            .add(ItemIds.INK_SAC)
            .add(ItemIds.GLOW_INK_SAC)
            .add(ItemIds.TURTLE_SCUTE)
            .add(ItemIds.ARMADILLO_SCUTE)
            .add(ItemIds.SLIME_BALL)
            .add(ItemIds.CLAY_BALL)
            .add(ItemIds.PRISMARINE_SHARD)
            .add(ItemIds.PRISMARINE_CRYSTALS)
            .add(ItemIds.NAUTILUS_SHELL)
            .add(ItemIds.HEART_OF_THE_SEA)
            .add(ItemIds.FIRE_CHARGE)
            .add(ItemIds.BLAZE_ROD)
            .add(ItemIds.BREEZE_ROD)
            .add(BlockItemIds.HEAVY_CORE.item())
            .add(ItemIds.NETHER_STAR)
            .add(ItemIds.ENDER_PEARL)
            .add(ItemIds.ENDER_EYE)
            .add(ItemIds.SHULKER_SHELL)
            .add(ItemIds.POPPED_CHORUS_FRUIT)
            .add(ItemIds.ECHO_SHARD)
            .add(ItemIds.DISC_FRAGMENT_5)
            .add(ItemGroupItemTags.DYES)
            .add(ItemIds.BOWL)
            .add(ItemIds.BRICK)
            .add(ItemIds.NETHER_BRICK)
            .add(ItemIds.RESIN_BRICK)
            .add(ItemIds.PAPER)
            .add(ItemIds.BOOK)
            .add(ItemIds.FIREWORK_STAR)
            .add(ItemGroupItemTags.BREWING_INGREDIENTS)
            .add(ItemGroupItemTags.BANNER_PATTERNS)
            .add(ItemTags.DECORATED_POT_SHERDS)
            .add(ItemGroupItemTags.SMITHING_TEMPLATES)
            .add(ItemIds.EXPERIENCE_BOTTLE)
            .add(ItemIds.TRIAL_KEY)
            .add(ItemIds.OMINOUS_TRIAL_KEY)
            .add(EnchantmentItemGroupEntry.of(items.getOrThrow(ItemIds.ENCHANTED_BOOK)))
            .build()
        );
        registerable.register(SPAWN_EGGS, ItemGroupEntryProvider.builder(items)
            .add(ItemGroupItemTags.SPAWNERS)
            .add(BlockItemIds.CREAKING_HEART.item())
            .add(ItemIds.ALLAY_SPAWN_EGG)
            .add(ItemIds.ARMADILLO_SPAWN_EGG)
            .add(ItemIds.AXOLOTL_SPAWN_EGG)
            .add(ItemIds.BAT_SPAWN_EGG)
            .add(ItemIds.BEE_SPAWN_EGG)
            .add(ItemIds.BLAZE_SPAWN_EGG)
            .add(ItemIds.BOGGED_SPAWN_EGG)
            .add(ItemIds.BREEZE_SPAWN_EGG)
            .add(ItemIds.CAMEL_SPAWN_EGG)
            .add(ItemIds.CAMEL_HUSK_SPAWN_EGG)
            .add(ItemIds.CAT_SPAWN_EGG)
            .add(ItemIds.CAVE_SPIDER_SPAWN_EGG)
            .add(ItemIds.CHICKEN_SPAWN_EGG)
            .add(ItemIds.COD_SPAWN_EGG)
            .add(ItemIds.COPPER_GOLEM_SPAWN_EGG)
            .add(ItemIds.COW_SPAWN_EGG)
            .add(ItemIds.CREAKING_SPAWN_EGG)
            .add(ItemIds.CREEPER_SPAWN_EGG)
            .add(ItemIds.DOLPHIN_SPAWN_EGG)
            .add(ItemIds.DONKEY_SPAWN_EGG)
            .add(ItemIds.DROWNED_SPAWN_EGG)
            .add(ItemIds.ELDER_GUARDIAN_SPAWN_EGG)
            .add(ItemIds.ENDERMAN_SPAWN_EGG)
            .add(ItemIds.ENDERMITE_SPAWN_EGG)
            .add(ItemIds.EVOKER_SPAWN_EGG)
            .add(ItemIds.FOX_SPAWN_EGG)
            .add(ItemIds.FROG_SPAWN_EGG)
            .add(ItemIds.GHAST_SPAWN_EGG)
            .add(ItemIds.GLOW_SQUID_SPAWN_EGG)
            .add(ItemIds.GOAT_SPAWN_EGG)
            .add(ItemIds.GUARDIAN_SPAWN_EGG)
            .add(ItemIds.HAPPY_GHAST_SPAWN_EGG)
            .add(ItemIds.HOGLIN_SPAWN_EGG)
            .add(ItemIds.HORSE_SPAWN_EGG)
            .add(ItemIds.HUSK_SPAWN_EGG)
            .add(ItemIds.IRON_GOLEM_SPAWN_EGG)
            .add(ItemIds.LLAMA_SPAWN_EGG)
            .add(ItemIds.MAGMA_CUBE_SPAWN_EGG)
            .add(ItemIds.MOOSHROOM_SPAWN_EGG)
            .add(ItemIds.MULE_SPAWN_EGG)
            .add(ItemIds.NAUTILUS_SPAWN_EGG)
            .add(ItemIds.OCELOT_SPAWN_EGG)
            .add(ItemIds.PANDA_SPAWN_EGG)
            .add(ItemIds.PARCHED_SPAWN_EGG)
            .add(ItemIds.PARROT_SPAWN_EGG)
            .add(ItemIds.PHANTOM_SPAWN_EGG)
            .add(ItemIds.PIG_SPAWN_EGG)
            .add(ItemIds.PIGLIN_SPAWN_EGG)
            .add(ItemIds.PIGLIN_BRUTE_SPAWN_EGG)
            .add(ItemIds.PILLAGER_SPAWN_EGG)
            .add(ItemIds.POLAR_BEAR_SPAWN_EGG)
            .add(ItemIds.PUFFERFISH_SPAWN_EGG)
            .add(ItemIds.RABBIT_SPAWN_EGG)
            .add(ItemIds.RAVAGER_SPAWN_EGG)
            .add(ItemIds.SALMON_SPAWN_EGG)
            .add(ItemIds.SHEEP_SPAWN_EGG)
            .add(ItemIds.SHULKER_SPAWN_EGG)
            .add(ItemIds.SILVERFISH_SPAWN_EGG)
            .add(ItemIds.SKELETON_SPAWN_EGG)
            .add(ItemIds.SKELETON_HORSE_SPAWN_EGG)
            .add(ItemIds.SLIME_SPAWN_EGG)
            .add(ItemIds.SNIFFER_SPAWN_EGG)
            .add(ItemIds.SNOW_GOLEM_SPAWN_EGG)
            .add(ItemIds.SPIDER_SPAWN_EGG)
            .add(ItemIds.SQUID_SPAWN_EGG)
            .add(ItemIds.STRAY_SPAWN_EGG)
            .add(ItemIds.STRIDER_SPAWN_EGG)
            .add(ItemIds.SULFUR_CUBE_SPAWN_EGG)
            .add(ItemIds.TADPOLE_SPAWN_EGG)
            .add(ItemIds.TRADER_LLAMA_SPAWN_EGG)
            .add(ItemIds.TROPICAL_FISH_SPAWN_EGG)
            .add(ItemIds.TURTLE_SPAWN_EGG)
            .add(ItemIds.VEX_SPAWN_EGG)
            .add(ItemIds.VILLAGER_SPAWN_EGG)
            .add(ItemIds.VINDICATOR_SPAWN_EGG)
            .add(ItemIds.WANDERING_TRADER_SPAWN_EGG)
            .add(ItemIds.WARDEN_SPAWN_EGG)
            .add(ItemIds.WITCH_SPAWN_EGG)
            .add(ItemIds.WITHER_SKELETON_SPAWN_EGG)
            .add(ItemIds.WOLF_SPAWN_EGG)
            .add(ItemIds.ZOGLIN_SPAWN_EGG)
            .add(ItemIds.ZOMBIE_SPAWN_EGG)
            .add(ItemIds.ZOMBIE_HORSE_SPAWN_EGG)
            .add(ItemIds.ZOMBIE_NAUTILUS_SPAWN_EGG)
            .add(ItemIds.ZOMBIE_VILLAGER_SPAWN_EGG)
            .add(ItemIds.ZOMBIFIED_PIGLIN_SPAWN_EGG)
            .build()
        );
        registerable.register(OP_BLOCKS, ItemGroupEntryProvider.builder(items)
            .addRequiresPermissions(BlockItemIds.COMMAND_BLOCK.item())
            .addRequiresPermissions(BlockItemIds.CHAIN_COMMAND_BLOCK.item())
            .addRequiresPermissions(BlockItemIds.REPEATING_COMMAND_BLOCK.item())
            .addRequiresPermissions(ItemIds.COMMAND_BLOCK_MINECART)
            .addRequiresPermissions(BlockItemIds.JIGSAW.item())
            .addRequiresPermissions(BlockItemIds.STRUCTURE_BLOCK.item())
            .addRequiresPermissions(BlockItemIds.STRUCTURE_VOID.item())
            .addRequiresPermissions(BlockItemIds.BARRIER.item())
            .addRequiresPermissions(ItemIds.DEBUG_STICK)
            .addRequiresPermissions(BlockItemIds.TEST_INSTANCE_BLOCK.item())
            .add(ItemGroupEntryProviders::testBlocks)
            .add(ItemGroupEntryProviders::lightBlocks)
            .add(PaintingVariantItemGroupEntry.unexpected(items.getOrThrow(ItemIds.PAINTING), PaintingVariantTags.PLACEABLE))
            .build()
        );
    }

    private static ResourceKey<ItemGroupEntryProvider> of(String id) {
        return ResourceKey.create(ItematicRegistries.ITEM_GROUP_ENTRY_PROVIDER, Identifier.withDefaultNamespace(id));
    }

    private static void flightDuration(ItemGroupEntryProvider.Builder builder) {
        for (int flightDuration : FireworkRocketItem.CRAFTABLE_DURATIONS) {
            builder.add(
                ItemIds.FIREWORK_ROCKET,
                DataComponentPatch.builder()
                    .set(DataComponents.FIREWORKS, new Fireworks(flightDuration, List.of()))
                    .build()
            );
        }
    }

    private static void ominousBottles(ItemGroupEntryProvider.Builder builder) {
        for (int amplifier = OminousBottleAmplifier.MIN_AMPLIFIER; amplifier <= OminousBottleAmplifier.MAX_AMPLIFIER; amplifier++) {
            builder.add(
                ItemIds.OMINOUS_BOTTLE,
                DataComponentPatch.builder()
                    .set(DataComponents.OMINOUS_BOTTLE_AMPLIFIER, new OminousBottleAmplifier(amplifier))
                    .build()
            );
        }
    }

    private static void testBlocks(ItemGroupEntryProvider.Builder builder) {
        for (TestBlockMode mode : TestBlockMode.values()) {
            builder.addRequiresPermissions(
                BlockItemIds.TEST_BLOCK.item(),
                DataComponentPatch.builder()
                    .set(DataComponents.BLOCK_STATE, BlockItemStateProperties.EMPTY.with(TestBlock.MODE, mode))
                    .build()
            );
        }
    }

    private static void lightBlocks(ItemGroupEntryProvider.Builder builder) {
        for (int level = LightBlock.MAX_LEVEL; level >= 0; level--) {
            builder.addRequiresPermissions(
                BlockItemIds.LIGHT.item(),
                DataComponentPatch.builder()
                    .set(DataComponents.BLOCK_STATE, BlockItemStateProperties.EMPTY.with(LightBlock.LEVEL, level))
                    .build()
            );
        }
    }
}
