package net.errorcraft.itematic.tags;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;

public class ItemGroupItemTags {
    public static final TagKey<Item> OAK_BUILDING_BLOCKS = of("oak_building_blocks");
    public static final TagKey<Item> SPRUCE_BUILDING_BLOCKS = of("spruce_building_blocks");
    public static final TagKey<Item> BIRCH_BUILDING_BLOCKS = of("birch_building_blocks");
    public static final TagKey<Item> JUNGLE_BUILDING_BLOCKS = of("jungle_building_blocks");
    public static final TagKey<Item> ACACIA_BUILDING_BLOCKS = of("acacia_building_blocks");
    public static final TagKey<Item> DARK_OAK_BUILDING_BLOCKS = of("dark_oak_building_blocks");
    public static final TagKey<Item> MANGROVE_BUILDING_BLOCKS = of("mangrove_building_blocks");
    public static final TagKey<Item> CHERRY_BUILDING_BLOCKS = of("cherry_building_blocks");
    public static final TagKey<Item> PALE_OAK_BUILDING_BLOCKS = of("pale_oak_building_blocks");
    public static final TagKey<Item> BAMBOO_BUILDING_BLOCKS = of("bamboo_building_blocks");
    public static final TagKey<Item> CRIMSON_BUILDING_BLOCKS = of("crimson_building_blocks");
    public static final TagKey<Item> WARPED_BUILDING_BLOCKS = of("warped_building_blocks");
    public static final TagKey<Item> WOODEN_BUILDING_BLOCKS = of("wooden_building_blocks");
    public static final TagKey<Item> STONE_BUILDING_BLOCKS = of("stone_building_blocks");
    public static final TagKey<Item> COBBLESTONE_BUILDING_BLOCKS = of("cobblestone_building_blocks");
    public static final TagKey<Item> MOSSY_COBBLESTONE_BUILDING_BLOCKS = of("mossy_cobblestone_building_blocks");
    public static final TagKey<Item> SMOOTH_STONE_BUILDING_BLOCKS = of("smooth_stone_building_blocks");
    public static final TagKey<Item> STONE_BRICK_BUILDING_BLOCKS = of("stone_brick_building_blocks");
    public static final TagKey<Item> MOSSY_STONE_BRICK_BUILDING_BLOCKS = of("mossy_stone_brick_building_blocks");
    public static final TagKey<Item> GRANITE_BUILDING_BLOCKS = of("granite_building_blocks");
    public static final TagKey<Item> POLISHED_GRANITE_BUILDING_BLOCKS = of("polished_granite_building_blocks");
    public static final TagKey<Item> DIORITE_BUILDING_BLOCKS = of("diorite_building_blocks");
    public static final TagKey<Item> POLISHED_DIORITE_BUILDING_BLOCKS = of("polished_diorite_building_blocks");
    public static final TagKey<Item> ANDESITE_BUILDING_BLOCKS = of("andesite_building_blocks");
    public static final TagKey<Item> POLISHED_ANDESITE_BUILDING_BLOCKS = of("polished_andesite_building_blocks");
    public static final TagKey<Item> COBBLED_DEEPSLATE_BUILDING_BLOCKS = of("cobbled_deepslate_building_blocks");
    public static final TagKey<Item> POLISHED_DEEPSLATE_BUILDING_BLOCKS = of("polished_deepslate_building_blocks");
    public static final TagKey<Item> DEEPSLATE_BRICK_BUILDING_BLOCKS = of("deepslate_brick_building_blocks");
    public static final TagKey<Item> DEEPSLATE_TILES_BUILDING_BLOCKS = of("deepslate_tiles_building_blocks");
    public static final TagKey<Item> TUFF_BUILDING_BLOCKS = of("tuff_building_blocks");
    public static final TagKey<Item> BRICK_BUILDING_BLOCKS = of("brick_building_blocks");
    public static final TagKey<Item> MUD_BRICK_BUILDING_BLOCKS = of("mud_brick_building_blocks");
    public static final TagKey<Item> RESIN_BRICK_BUILDING_BLOCKS = of("resin_brick_building_blocks");
    public static final TagKey<Item> SANDSTONE_BUILDING_BLOCKS = of("sandstone_building_blocks");
    public static final TagKey<Item> SMOOTH_SANDSTONE_BUILDING_BLOCKS = of("smooth_sandstone_building_blocks");
    public static final TagKey<Item> CUT_SANDSTONE_BUILDING_BLOCKS = of("cut_sandstone_building_blocks");
    public static final TagKey<Item> RED_SANDSTONE_BUILDING_BLOCKS = of("red_sandstone_building_blocks");
    public static final TagKey<Item> SMOOTH_RED_SANDSTONE_BUILDING_BLOCKS = of("smooth_red_sandstone_building_blocks");
    public static final TagKey<Item> CUT_RED_SANDSTONE_BUILDING_BLOCKS = of("cut_red_sandstone_building_blocks");
    public static final TagKey<Item> PRISMARINE_BUILDING_BLOCKS = of("prismarine_building_blocks");
    public static final TagKey<Item> PRISMARINE_BRICK_BUILDING_BLOCKS = of("prismarine_brick_building_blocks");
    public static final TagKey<Item> DARK_PRISMARINE_BUILDING_BLOCKS = of("dark_prismarine_building_blocks");
    public static final TagKey<Item> NETHER_BRICK_BUILDING_BLOCKS = of("nether_brick_building_blocks");
    public static final TagKey<Item> RED_NETHER_BRICK_BUILDING_BLOCKS = of("red_nether_brick_building_blocks");
    public static final TagKey<Item> BASALT_BUILDING_BLOCKS = of("basalt_building_blocks");
    public static final TagKey<Item> BLACKSTONE_BUILDING_BLOCKS = of("blackstone_building_blocks");
    public static final TagKey<Item> POLISHED_BLACKSTONE_BUILDING_BLOCKS = of("polished_blackstone_building_blocks");
    public static final TagKey<Item> POLISHED_BLACKSTONE_BRICK_BUILDING_BLOCKS = of("polished_blackstone_brick_building_blocks");
    public static final TagKey<Item> END_STONE_BRICK_BUILDING_BLOCKS = of("end_stone_brick_building_blocks");
    public static final TagKey<Item> PURPUR_BUILDING_BLOCKS = of("purpur_building_blocks");
    public static final TagKey<Item> STONE_LIKE_BUILDING_BLOCKS = of("stone_like_building_blocks");
    public static final TagKey<Item> IRON_BUILDING_BLOCKS = of("iron_building_blocks");
    public static final TagKey<Item> GOLD_BUILDING_BLOCKS = of("gold_building_blocks");
    public static final TagKey<Item> QUARTZ_BUILDING_BLOCKS = of("quartz_building_blocks");
    public static final TagKey<Item> SMOOTH_QUARTZ_BUILDING_BLOCKS = of("smooth_quartz_building_blocks");
    public static final TagKey<Item> COPPER_BUILDING_BLOCKS = of("copper_building_blocks");
    public static final TagKey<Item> EXPOSED_COPPER_BUILDING_BLOCKS = of("exposed_copper_building_blocks");
    public static final TagKey<Item> WEATHERED_COPPER_BUILDING_BLOCKS = of("weathered_copper_building_blocks");
    public static final TagKey<Item> OXIDIZED_COPPER_BUILDING_BLOCKS = of("oxidized_copper_building_blocks");
    public static final TagKey<Item> WAXED_COPPER_BUILDING_BLOCKS = of("waxed_copper_building_blocks");
    public static final TagKey<Item> WAXED_EXPOSED_COPPER_BUILDING_BLOCKS = of("waxed_exposed_copper_building_blocks");
    public static final TagKey<Item> WAXED_WEATHERED_COPPER_BUILDING_BLOCKS = of("waxed_weathered_copper_building_blocks");
    public static final TagKey<Item> WAXED_OXIDIZED_COPPER_BUILDING_BLOCKS = of("waxed_oxidized_copper_building_blocks");
    public static final TagKey<Item> COPPER_LIKE_BUILDING_BLOCKS = of("copper_like_building_blocks");
    public static final TagKey<Item> WOOL = of("wool");
    public static final TagKey<Item> WOOL_CARPETS = of("wool_carpets");
    public static final TagKey<Item> TERRACOTTA = of("terracotta");
    public static final TagKey<Item> CONCRETE = of("concrete");
    public static final TagKey<Item> CONCRETE_POWDER = of("concrete_powder");
    public static final TagKey<Item> GLAZED_TERRACOTTA = of("glazed_terracotta");
    public static final TagKey<Item> GLASS = of("glass");
    public static final TagKey<Item> GLASS_PANES = of("glass_panes");
    public static final TagKey<Item> SHULKER_BOXES = of("shulker_boxes");
    public static final TagKey<Item> BEDS = of("beds");
    public static final TagKey<Item> CANDLES = of("candles");
    public static final TagKey<Item> BANNERS = of("banners");
    public static final TagKey<Item> GRASS_LIKE_BLOCKS = of("grass_like_blocks");
    public static final TagKey<Item> DIRT_LIKE_BLOCKS = of("dirt_like_blocks");
    public static final TagKey<Item> SAND_BLOCKS = of("sand_blocks");
    public static final TagKey<Item> ICE_BLOCKS = of("ice_blocks");
    public static final TagKey<Item> SNOW_BLOCKS = of("snow_blocks");
    public static final TagKey<Item> MOSS_BLOCKS = of("moss_blocks");
    public static final TagKey<Item> STONE_LIKE_BLOCKS = of("stone_like_blocks");
    public static final TagKey<Item> NETHER_BLOCKS = of("nether_blocks");
    public static final TagKey<Item> GOLD_OVERWORLD_ORES = of("gold_overworld_ores");
    public static final TagKey<Item> ORE_LIKE_BLOCKS = of("ore_like_blocks");
    public static final TagKey<Item> AMETHYST_BLOCKS = of("amethyst_blocks");
    public static final TagKey<Item> LOG_LIKE_BLOCKS = of("log_like_blocks");
    public static final TagKey<Item> LEAVES = of("leaves");
    public static final TagKey<Item> MUSHROOM_LIKE_BLOCKS = of("mushroom_like_blocks");
    public static final TagKey<Item> SAPLINGS = of("saplings");
    public static final TagKey<Item> PLANTS = of("plants");
    public static final TagKey<Item> EGG_LIKE_BLOCKS = of("egg_like_blocks");
    public static final TagKey<Item> CORAL_BLOCKS = of("coral_blocks");
    public static final TagKey<Item> CORAL = of("coral");
    public static final TagKey<Item> CORAL_FANS = of("coral_fans");
    public static final TagKey<Item> SEEDS = of("seeds");
    public static final TagKey<Item> WATER_BLOCKS = of("water_blocks");
    public static final TagKey<Item> PUMPKINS = of("pumpkins");
    public static final TagKey<Item> FROGLIGHTS = of("froglights");
    public static final TagKey<Item> SCULK = of("sculk");
    public static final TagKey<Item> TORCHES = of("torches");
    public static final TagKey<Item> LANTERNS = of("lanterns");
    public static final TagKey<Item> CHAINS = of("chains");
    public static final TagKey<Item> LIGHT_EMITTING_BLOCKS = of("light_emitting_blocks");
    public static final TagKey<Item> LIGHTNING_RODS = of("lightning_rods");
    public static final TagKey<Item> SHELVES = of("shelves");
    public static final TagKey<Item> SIGNS = of("signs");
    public static final TagKey<Item> HEADS = of("heads");
    public static final TagKey<Item> COPPER_GOLEMS = of("copper_golems");
    public static final TagKey<Item> INFESTED_BLOCKS = of("infested_blocks");
    public static final TagKey<Item> WOODEN_CHESTS = of("wooden_chests");
    public static final TagKey<Item> COPPER_CHESTS = of("copper_chests");
    public static final TagKey<Item> CHESTS = of("chests");
    public static final TagKey<Item> RAILS = of("rails");
    public static final TagKey<Item> MINECARTS = of("minecarts");
    public static final TagKey<Item> TOOLS = of("tools");
    public static final TagKey<Item> BUCKETS = of("buckets");
    public static final TagKey<Item> BUNDLES = of("bundles");
    public static final TagKey<Item> HARNESSES = of("harnesses");
    public static final TagKey<Item> BOATS = of("boats");
    public static final TagKey<Item> MUSIC_DISCS = of("music_discs");
    public static final TagKey<Item> SWORDS = of("swords");
    public static final TagKey<Item> AXES = of("axes");
    public static final TagKey<Item> SPEARS = of("spears");
    public static final TagKey<Item> ARMOR = of("armor");
    public static final TagKey<Item> HORSE_ARMOR = of("horse_armor");
    public static final TagKey<Item> NAUTILUS_ARMOR = of("nautilus_armor");
    public static final TagKey<Item> NUGGETS = of("nuggets");
    public static final TagKey<Item> EGGS = of("eggs");
    public static final TagKey<Item> FOOD = of("food");
    public static final TagKey<Item> DYES = of("dyes");
    public static final TagKey<Item> BREWING_INGREDIENTS = of("brewing_ingredients");
    public static final TagKey<Item> BANNER_PATTERNS = of("banner_patterns");
    public static final TagKey<Item> SMITHING_TEMPLATES = of("smithing_templates");
    public static final TagKey<Item> SPAWNERS = of("spawners");

    private ItemGroupItemTags() {}

    private static TagKey<Item> of(String id) {
        return TagKey.create(Registries.ITEM, Identifier.withDefaultNamespace("item_group/" + id));
    }
}
