package net.errorcraft.itematic.entity;

import net.minecraft.entity.EntityType;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.Identifier;

public class EntityTypeKeys {
    public static final RegistryKey<EntityType<?>> ACACIA_BOAT = of("acacia_boat");
    public static final RegistryKey<EntityType<?>> ACACIA_CHEST_BOAT = of("acacia_chest_boat");
    public static final RegistryKey<EntityType<?>> ALLAY = of("allay");
    public static final RegistryKey<EntityType<?>> ARMADILLO = of("armadillo");
    public static final RegistryKey<EntityType<?>> ARMOR_STAND = of("armor_stand");
    public static final RegistryKey<EntityType<?>> ARROW = of("arrow");
    public static final RegistryKey<EntityType<?>> AXOLOTL = of("axolotl");
    public static final RegistryKey<EntityType<?>> BAMBOO_CHEST_RAFT = of("bamboo_chest_raft");
    public static final RegistryKey<EntityType<?>> BAMBOO_RAFT = of("bamboo_raft");
    public static final RegistryKey<EntityType<?>> BAT = of("bat");
    public static final RegistryKey<EntityType<?>> BEE = of("bee");
    public static final RegistryKey<EntityType<?>> BIRCH_BOAT = of("birch_boat");
    public static final RegistryKey<EntityType<?>> BIRCH_CHEST_BOAT = of("birch_chest_boat");
    public static final RegistryKey<EntityType<?>> BLAZE = of("blaze");
    public static final RegistryKey<EntityType<?>> BOGGED = of("bogged");
    public static final RegistryKey<EntityType<?>> BREEZE = of("breeze");
    public static final RegistryKey<EntityType<?>> CAMEL = of("camel");
    public static final RegistryKey<EntityType<?>> CAT = of("cat");
    public static final RegistryKey<EntityType<?>> CAVE_SPIDER = of("cave_spider");
    public static final RegistryKey<EntityType<?>> CHERRY_BOAT = of("cherry_boat");
    public static final RegistryKey<EntityType<?>> CHERRY_CHEST_BOAT = of("cherry_chest_boat");
    public static final RegistryKey<EntityType<?>> CHEST_MINECART = of("chest_minecart");
    public static final RegistryKey<EntityType<?>> CHICKEN = of("chicken");
    public static final RegistryKey<EntityType<?>> COD = of("cod");
    public static final RegistryKey<EntityType<?>> COMMAND_BLOCK_MINECART = of("command_block_minecart");
    public static final RegistryKey<EntityType<?>> COW = of("cow");
    public static final RegistryKey<EntityType<?>> CREAKING = of("creaking");
    public static final RegistryKey<EntityType<?>> CREEPER = of("creeper");
    public static final RegistryKey<EntityType<?>> DARK_OAK_BOAT = of("dark_oak_boat");
    public static final RegistryKey<EntityType<?>> DARK_OAK_CHEST_BOAT = of("dark_oak_chest_boat");
    public static final RegistryKey<EntityType<?>> DOLPHIN = of("dolphin");
    public static final RegistryKey<EntityType<?>> DONKEY = of("donkey");
    public static final RegistryKey<EntityType<?>> DROWNED = of("drowned");
    public static final RegistryKey<EntityType<?>> EGG = of("egg");
    public static final RegistryKey<EntityType<?>> ELDER_GUARDIAN = of("elder_guardian");
    public static final RegistryKey<EntityType<?>> ENDERMAN = of("enderman");
    public static final RegistryKey<EntityType<?>> ENDERMITE = of("endermite");
    public static final RegistryKey<EntityType<?>> ENDER_DRAGON = of("ender_dragon");
    public static final RegistryKey<EntityType<?>> ENDER_PEARL = of("ender_pearl");
    public static final RegistryKey<EntityType<?>> END_CRYSTAL = of("end_crystal");
    public static final RegistryKey<EntityType<?>> EVOKER = of("evoker");
    public static final RegistryKey<EntityType<?>> EXPERIENCE_BOTTLE = of("experience_bottle");
    public static final RegistryKey<EntityType<?>> EYE_OF_ENDER = of("eye_of_ender");
    public static final RegistryKey<EntityType<?>> FIREWORK_ROCKET = of("firework_rocket");
    public static final RegistryKey<EntityType<?>> FOX = of("fox");
    public static final RegistryKey<EntityType<?>> FROG = of("frog");
    public static final RegistryKey<EntityType<?>> FURNACE_MINECART = of("furnace_minecart");
    public static final RegistryKey<EntityType<?>> GHAST = of("ghast");
    public static final RegistryKey<EntityType<?>> GLOW_ITEM_FRAME = of("glow_item_frame");
    public static final RegistryKey<EntityType<?>> GLOW_SQUID = of("glow_squid");
    public static final RegistryKey<EntityType<?>> GOAT = of("goat");
    public static final RegistryKey<EntityType<?>> GUARDIAN = of("guardian");
    public static final RegistryKey<EntityType<?>> HOGLIN = of("hoglin");
    public static final RegistryKey<EntityType<?>> HOPPER_MINECART = of("hopper_minecart");
    public static final RegistryKey<EntityType<?>> HORSE = of("horse");
    public static final RegistryKey<EntityType<?>> HUSK = of("husk");
    public static final RegistryKey<EntityType<?>> IRON_GOLEM = of("iron_golem");
    public static final RegistryKey<EntityType<?>> ITEM_FRAME = of("item_frame");
    public static final RegistryKey<EntityType<?>> JUNGLE_BOAT = of("jungle_boat");
    public static final RegistryKey<EntityType<?>> JUNGLE_CHEST_BOAT = of("jungle_chest_boat");
    public static final RegistryKey<EntityType<?>> LINGERING_POTION = of("lingering_potion");
    public static final RegistryKey<EntityType<?>> LLAMA = of("llama");
    public static final RegistryKey<EntityType<?>> MAGMA_CUBE = of("magma_cube");
    public static final RegistryKey<EntityType<?>> MANGROVE_BOAT = of("mangrove_boat");
    public static final RegistryKey<EntityType<?>> MANGROVE_CHEST_BOAT = of("mangrove_chest_boat");
    public static final RegistryKey<EntityType<?>> MINECART = of("minecart");
    public static final RegistryKey<EntityType<?>> MOOSHROOM = of("mooshroom");
    public static final RegistryKey<EntityType<?>> MULE = of("mule");
    public static final RegistryKey<EntityType<?>> OAK_BOAT = of("oak_boat");
    public static final RegistryKey<EntityType<?>> OAK_CHEST_BOAT = of("oak_chest_boat");
    public static final RegistryKey<EntityType<?>> OCELOT = of("ocelot");
    public static final RegistryKey<EntityType<?>> PAINTING = of("painting");
    public static final RegistryKey<EntityType<?>> PALE_OAK_BOAT = of("pale_oak_boat");
    public static final RegistryKey<EntityType<?>> PALE_OAK_CHEST_BOAT = of("pale_oak_chest_boat");
    public static final RegistryKey<EntityType<?>> PANDA = of("panda");
    public static final RegistryKey<EntityType<?>> PARROT = of("parrot");
    public static final RegistryKey<EntityType<?>> PHANTOM = of("phantom");
    public static final RegistryKey<EntityType<?>> PIG = of("pig");
    public static final RegistryKey<EntityType<?>> PIGLIN = of("piglin");
    public static final RegistryKey<EntityType<?>> PIGLIN_BRUTE = of("piglin_brute");
    public static final RegistryKey<EntityType<?>> PILLAGER = of("pillager");
    public static final RegistryKey<EntityType<?>> POLAR_BEAR = of("polar_bear");
    public static final RegistryKey<EntityType<?>> PUFFERFISH = of("pufferfish");
    public static final RegistryKey<EntityType<?>> RABBIT = of("rabbit");
    public static final RegistryKey<EntityType<?>> RAVAGER = of("ravager");
    public static final RegistryKey<EntityType<?>> SALMON = of("salmon");
    public static final RegistryKey<EntityType<?>> SHEEP = of("sheep");
    public static final RegistryKey<EntityType<?>> SHULKER = of("shulker");
    public static final RegistryKey<EntityType<?>> SILVERFISH = of("silverfish");
    public static final RegistryKey<EntityType<?>> SKELETON = of("skeleton");
    public static final RegistryKey<EntityType<?>> SKELETON_HORSE = of("skeleton_horse");
    public static final RegistryKey<EntityType<?>> SLIME = of("slime");
    public static final RegistryKey<EntityType<?>> SMALL_FIREBALL = of("small_fireball");
    public static final RegistryKey<EntityType<?>> SNIFFER = of("sniffer");
    public static final RegistryKey<EntityType<?>> SNOWBALL = of("snowball");
    public static final RegistryKey<EntityType<?>> SNOW_GOLEM = of("snow_golem");
    public static final RegistryKey<EntityType<?>> SPECTRAL_ARROW = of("spectral_arrow");
    public static final RegistryKey<EntityType<?>> SPIDER = of("spider");
    public static final RegistryKey<EntityType<?>> SPLASH_POTION = of("splash_potion");
    public static final RegistryKey<EntityType<?>> SPRUCE_BOAT = of("spruce_boat");
    public static final RegistryKey<EntityType<?>> SPRUCE_CHEST_BOAT = of("spruce_chest_boat");
    public static final RegistryKey<EntityType<?>> SQUID = of("squid");
    public static final RegistryKey<EntityType<?>> STRAY = of("stray");
    public static final RegistryKey<EntityType<?>> STRIDER = of("strider");
    public static final RegistryKey<EntityType<?>> TADPOLE = of("tadpole");
    public static final RegistryKey<EntityType<?>> TNT = of("tnt");
    public static final RegistryKey<EntityType<?>> TNT_MINECART = of("tnt_minecart");
    public static final RegistryKey<EntityType<?>> TRADER_LLAMA = of("trader_llama");
    public static final RegistryKey<EntityType<?>> TRIDENT = of("trident");
    public static final RegistryKey<EntityType<?>> TROPICAL_FISH = of("tropical_fish");
    public static final RegistryKey<EntityType<?>> TURTLE = of("turtle");
    public static final RegistryKey<EntityType<?>> VEX = of("vex");
    public static final RegistryKey<EntityType<?>> VILLAGER = of("villager");
    public static final RegistryKey<EntityType<?>> VINDICATOR = of("vindicator");
    public static final RegistryKey<EntityType<?>> WANDERING_TRADER = of("wandering_trader");
    public static final RegistryKey<EntityType<?>> WARDEN = of("warden");
    public static final RegistryKey<EntityType<?>> WIND_CHARGE = of("wind_charge");
    public static final RegistryKey<EntityType<?>> WITCH = of("witch");
    public static final RegistryKey<EntityType<?>> WITHER = of("wither");
    public static final RegistryKey<EntityType<?>> WITHER_SKELETON = of("wither_skeleton");
    public static final RegistryKey<EntityType<?>> WOLF = of("wolf");
    public static final RegistryKey<EntityType<?>> ZOGLIN = of("zoglin");
    public static final RegistryKey<EntityType<?>> ZOMBIE = of("zombie");
    public static final RegistryKey<EntityType<?>> ZOMBIE_HORSE = of("zombie_horse");
    public static final RegistryKey<EntityType<?>> ZOMBIE_VILLAGER = of("zombie_villager");
    public static final RegistryKey<EntityType<?>> ZOMBIFIED_PIGLIN = of("zombified_piglin");

    private EntityTypeKeys() {}

    private static RegistryKey<EntityType<?>> of(String id) {
        return RegistryKey.of(RegistryKeys.ENTITY_TYPE, Identifier.ofVanilla(id));
    }
}
