package net.errorcraft.itematic.item.group.entry.provider;

import net.errorcraft.itematic.item.ItemKeys;
import net.errorcraft.itematic.item.ItematicItemTags;
import net.errorcraft.itematic.item.group.entry.ItemGroupEntry;
import net.errorcraft.itematic.item.group.entry.entries.*;
import net.errorcraft.itematic.village.raid.RaidUtil;
import net.minecraft.block.LightBlock;
import net.minecraft.block.TestBlock;
import net.minecraft.block.entity.BannerPattern;
import net.minecraft.block.enums.TestBlockMode;
import net.minecraft.component.ComponentChanges;
import net.minecraft.component.DataComponentTypes;
import net.minecraft.component.type.FireworksComponent;
import net.minecraft.component.type.OminousBottleAmplifierComponent;
import net.minecraft.item.FireworkRocketItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registerable;
import net.minecraft.registry.RegistryEntryLookup;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.entry.RegistryEntry;
import net.minecraft.registry.tag.InstrumentTags;
import net.minecraft.registry.tag.ItemTags;
import net.minecraft.registry.tag.PaintingVariantTags;

import java.util.ArrayList;
import java.util.List;

public class ItemGroupEntryProviders {
    private ItemGroupEntryProviders() {}

    public static void bootstrap(Registerable<ItemGroupEntryProvider> registerable) {
        RegistryEntryLookup<Item> items = registerable.getRegistryLookup(RegistryKeys.ITEM);
        RegistryEntryLookup<BannerPattern> bannerPatterns = registerable.getRegistryLookup(RegistryKeys.BANNER_PATTERN);

        registerable.register(ItemGroupEntryProviderKeys.BUILDING_BLOCKS, ItemGroupEntryProvider.builder()
            .add(ItematicItemTags.WOODEN_BUILDING_BLOCKS)
            .add(ItematicItemTags.STONE_LIKE_BUILDING_BLOCKS)
            .add(items.getOrThrow(ItemKeys.COAL_BLOCK))
            .add(ItematicItemTags.IRON_BUILDING_BLOCKS)
            .add(ItematicItemTags.GOLD_BUILDING_BLOCKS)
            .add(items.getOrThrow(ItemKeys.REDSTONE_BLOCK))
            .add(items.getOrThrow(ItemKeys.EMERALD_BLOCK))
            .add(items.getOrThrow(ItemKeys.LAPIS_BLOCK))
            .add(items.getOrThrow(ItemKeys.DIAMOND_BLOCK))
            .add(items.getOrThrow(ItemKeys.NETHERITE_BLOCK))
            .add(ItematicItemTags.QUARTZ_BUILDING_BLOCKS)
            .add(ItematicItemTags.SMOOTH_QUARTZ_BUILDING_BLOCKS)
            .add(items.getOrThrow(ItemKeys.AMETHYST_BLOCK))
            .add(ItematicItemTags.COPPER_LIKE_BUILDING_BLOCKS)
            .build()
        );
        registerable.register(ItemGroupEntryProviderKeys.COLORED_BLOCKS, ItemGroupEntryProvider.builder()
            .add(ItematicItemTags.WOOL)
            .add(ItematicItemTags.WOOL_CARPETS)
            .add(ItematicItemTags.TERRACOTTA)
            .add(ItematicItemTags.CONCRETE)
            .add(ItematicItemTags.CONCRETE_POWDER)
            .add(ItematicItemTags.GLAZED_TERRACOTTA)
            .add(ItematicItemTags.GLASS)
            .add(ItematicItemTags.GLASS_PANES)
            .add(ItematicItemTags.ITEM_GROUP_SHULKER_BOXES)
            .add(ItematicItemTags.BEDS)
            .add(ItematicItemTags.CANDLES)
            .add(ItematicItemTags.BANNERS)
            .build()
        );
        registerable.register(ItemGroupEntryProviderKeys.NATURAL_BLOCKS, ItemGroupEntryProvider.builder()
            .add(ItematicItemTags.GRASS_LIKE_BLOCKS)
            .add(ItematicItemTags.DIRT_LIKE_BLOCKS)
            .add(items.getOrThrow(ItemKeys.GRAVEL))
            .add(ItematicItemTags.SAND_BLOCKS)
            .add(ItematicItemTags.ICE_BLOCKS)
            .add(ItematicItemTags.SNOW_BLOCKS)
            .add(ItematicItemTags.MOSS_BLOCKS)
            .add(ItematicItemTags.STONE_LIKE_BLOCKS)
            .add(ItematicItemTags.NETHER_BLOCKS)
            .add(items.getOrThrow(ItemKeys.END_STONE))
            .add(ItematicItemTags.ORE_LIKE_BLOCKS)
            .add(items.getOrThrow(ItemKeys.GLOWSTONE))
            .add(ItematicItemTags.AMETHYST_BLOCKS)
            .add(ItematicItemTags.LOG_LIKE_BLOCKS)
            .add(ItematicItemTags.LEAVES)
            .add(ItematicItemTags.MUSHROOM_LIKE_BLOCKS)
            .add(ItematicItemTags.SAPLINGS)
            .add(ItematicItemTags.PLANTS)
            .add(ItematicItemTags.EGG_LIKE_BLOCKS)
            .add(items.getOrThrow(ItemKeys.DRIED_GHAST))
            .add(ItematicItemTags.SEEDS)
            .add(ItematicItemTags.WATER_BLOCKS)
            .add(items.getOrThrow(ItemKeys.SPONGE))
            .add(items.getOrThrow(ItemKeys.WET_SPONGE))
            .add(items.getOrThrow(ItemKeys.MELON))
            .add(ItematicItemTags.PUMPKINS)
            .add(items.getOrThrow(ItemKeys.HAY_BLOCK))
            .add(items.getOrThrow(ItemKeys.BEE_NEST))
            .add(items.getOrThrow(ItemKeys.HONEYCOMB_BLOCK))
            .add(items.getOrThrow(ItemKeys.SLIME_BLOCK))
            .add(items.getOrThrow(ItemKeys.HONEY_BLOCK))
            .add(items.getOrThrow(ItemKeys.RESIN_BLOCK))
            .add(ItematicItemTags.FROGLIGHTS)
            .add(ItematicItemTags.SCULK)
            .add(items.getOrThrow(ItemKeys.COBWEB))
            .add(items.getOrThrow(ItemKeys.BEDROCK))
            .build()
        );
        registerable.register(ItemGroupEntryProviderKeys.FUNCTIONAL_BLOCKS, ItemGroupEntryProvider.builder()
            .add(ItematicItemTags.TORCHES)
            .add(ItematicItemTags.LANTERNS)
            .add(ItematicItemTags.CHAINS)
            .add(ItematicItemTags.LIGHT_EMITTING_BLOCKS)
            .add(items.getOrThrow(ItemKeys.CRAFTING_TABLE))
            .add(items.getOrThrow(ItemKeys.STONECUTTER))
            .add(items.getOrThrow(ItemKeys.CARTOGRAPHY_TABLE))
            .add(items.getOrThrow(ItemKeys.FLETCHING_TABLE))
            .add(items.getOrThrow(ItemKeys.SMITHING_TABLE))
            .add(items.getOrThrow(ItemKeys.GRINDSTONE))
            .add(items.getOrThrow(ItemKeys.LOOM))
            .add(items.getOrThrow(ItemKeys.FURNACE))
            .add(items.getOrThrow(ItemKeys.SMOKER))
            .add(items.getOrThrow(ItemKeys.BLAST_FURNACE))
            .add(items.getOrThrow(ItemKeys.CAMPFIRE))
            .add(items.getOrThrow(ItemKeys.SOUL_CAMPFIRE))
            .add(items.getOrThrow(ItemKeys.ANVIL))
            .add(items.getOrThrow(ItemKeys.CHIPPED_ANVIL))
            .add(items.getOrThrow(ItemKeys.DAMAGED_ANVIL))
            .add(items.getOrThrow(ItemKeys.COMPOSTER))
            .add(items.getOrThrow(ItemKeys.NOTE_BLOCK))
            .add(items.getOrThrow(ItemKeys.JUKEBOX))
            .add(items.getOrThrow(ItemKeys.ENCHANTING_TABLE))
            .add(items.getOrThrow(ItemKeys.END_CRYSTAL))
            .add(items.getOrThrow(ItemKeys.BREWING_STAND))
            .add(items.getOrThrow(ItemKeys.CAULDRON))
            .add(items.getOrThrow(ItemKeys.BELL))
            .add(items.getOrThrow(ItemKeys.BEACON))
            .add(items.getOrThrow(ItemKeys.CONDUIT))
            .add(items.getOrThrow(ItemKeys.LODESTONE))
            .add(items.getOrThrow(ItemKeys.LADDER))
            .add(items.getOrThrow(ItemKeys.SCAFFOLDING))
            .add(items.getOrThrow(ItemKeys.BEE_NEST))
            .add(items.getOrThrow(ItemKeys.BEEHIVE))
            .add(items.getOrThrow(ItemKeys.SUSPICIOUS_SAND))
            .add(items.getOrThrow(ItemKeys.SUSPICIOUS_GRAVEL))
            .add(ItematicItemTags.LIGHTNING_RODS)
            .add(items.getOrThrow(ItemKeys.FLOWER_POT))
            .add(items.getOrThrow(ItemKeys.DECORATED_POT))
            .add(items.getOrThrow(ItemKeys.ARMOR_STAND))
            .add(items.getOrThrow(ItemKeys.ITEM_FRAME))
            .add(items.getOrThrow(ItemKeys.GLOW_ITEM_FRAME))
            .add(items.getOrThrow(ItemKeys.PAINTING))
            .add(PaintingVariantItemGroupEntry.expected(
                items.getOrThrow(ItemKeys.PAINTING),
                PaintingVariantTags.PLACEABLE
            ))
            .add(items.getOrThrow(ItemKeys.BOOKSHELF))
            .add(items.getOrThrow(ItemKeys.CHISELED_BOOKSHELF))
            .add(ItematicItemTags.SHELVES)
            .add(items.getOrThrow(ItemKeys.LECTERN))
            .add(items.getOrThrow(ItemKeys.TINTED_GLASS))
            .add(ItematicItemTags.SIGNS)
            .add(items.getOrThrow(ItemKeys.CHEST))
            .add(items.getOrThrow(ItemKeys.BARREL))
            .add(items.getOrThrow(ItemKeys.ENDER_CHEST))
            .add(ItematicItemTags.ITEM_GROUP_SHULKER_BOXES)
            .add(items.getOrThrow(ItemKeys.RESPAWN_ANCHOR))
            .add(ItematicItemTags.BEDS)
            .add(ItematicItemTags.CANDLES)
            .add(ItematicItemTags.BANNERS)
            .add(StackItemGroupEntry.fromStack(RaidUtil.getOminousBanner(items, bannerPatterns)))
            .add(ItematicItemTags.HEADS)
            .add(items.getOrThrow(ItemKeys.DRAGON_EGG))
            .add(items.getOrThrow(ItemKeys.END_PORTAL_FRAME))
            .add(items.getOrThrow(ItemKeys.ENDER_EYE))
            .add(items.getOrThrow(ItemKeys.VAULT))
            .add(ItematicItemTags.COPPER_GOLEMS)
            .add(ItematicItemTags.INFESTED_BLOCKS)
            .build()
        );
        registerable.register(ItemGroupEntryProviderKeys.REDSTONE_BLOCKS, ItemGroupEntryProvider.builder()
            .add(items.getOrThrow(ItemKeys.REDSTONE))
            .add(items.getOrThrow(ItemKeys.REDSTONE_TORCH))
            .add(items.getOrThrow(ItemKeys.REDSTONE_BLOCK))
            .add(items.getOrThrow(ItemKeys.REPEATER))
            .add(items.getOrThrow(ItemKeys.COMPARATOR))
            .add(items.getOrThrow(ItemKeys.TARGET))
            .add(items.getOrThrow(ItemKeys.COPPER_BULB))
            .add(items.getOrThrow(ItemKeys.EXPOSED_COPPER_BULB))
            .add(items.getOrThrow(ItemKeys.WEATHERED_COPPER_BULB))
            .add(items.getOrThrow(ItemKeys.OXIDIZED_COPPER_BULB))
            .add(items.getOrThrow(ItemKeys.LEVER))
            .add(items.getOrThrow(ItemKeys.OAK_BUTTON))
            .add(items.getOrThrow(ItemKeys.STONE_BUTTON))
            .add(items.getOrThrow(ItemKeys.OAK_PRESSURE_PLATE))
            .add(items.getOrThrow(ItemKeys.STONE_PRESSURE_PLATE))
            .add(items.getOrThrow(ItemKeys.LIGHT_WEIGHTED_PRESSURE_PLATE))
            .add(items.getOrThrow(ItemKeys.HEAVY_WEIGHTED_PRESSURE_PLATE))
            .add(items.getOrThrow(ItemKeys.SCULK_SENSOR))
            .add(items.getOrThrow(ItemKeys.CALIBRATED_SCULK_SENSOR))
            .add(items.getOrThrow(ItemKeys.SCULK_SHRIEKER))
            .add(items.getOrThrow(ItemKeys.AMETHYST_BLOCK))
            .add(items.getOrThrow(ItemKeys.WHITE_WOOL))
            .add(items.getOrThrow(ItemKeys.TRIPWIRE_HOOK))
            .add(items.getOrThrow(ItemKeys.STRING))
            .add(items.getOrThrow(ItemKeys.LECTERN))
            .add(items.getOrThrow(ItemKeys.DAYLIGHT_DETECTOR))
            .add(ItematicItemTags.LIGHTNING_RODS)
            .add(items.getOrThrow(ItemKeys.PISTON))
            .add(items.getOrThrow(ItemKeys.STICKY_PISTON))
            .add(items.getOrThrow(ItemKeys.SLIME_BLOCK))
            .add(items.getOrThrow(ItemKeys.HONEY_BLOCK))
            .add(items.getOrThrow(ItemKeys.DISPENSER))
            .add(items.getOrThrow(ItemKeys.DROPPER))
            .add(items.getOrThrow(ItemKeys.CRAFTER))
            .add(items.getOrThrow(ItemKeys.HOPPER))
            .add(ItematicItemTags.CHESTS)
            .add(items.getOrThrow(ItemKeys.BARREL))
            .add(items.getOrThrow(ItemKeys.CHISELED_BOOKSHELF))
            .add(ItematicItemTags.SHELVES)
            .add(items.getOrThrow(ItemKeys.FURNACE))
            .add(items.getOrThrow(ItemKeys.TRAPPED_CHEST))
            .add(items.getOrThrow(ItemKeys.JUKEBOX))
            .add(items.getOrThrow(ItemKeys.DECORATED_POT))
            .add(items.getOrThrow(ItemKeys.OBSERVER))
            .add(items.getOrThrow(ItemKeys.NOTE_BLOCK))
            .add(items.getOrThrow(ItemKeys.COMPOSTER))
            .add(items.getOrThrow(ItemKeys.CAULDRON))
            .add(ItematicItemTags.RAILS)
            .add(ItematicItemTags.MINECARTS)
            .add(items.getOrThrow(ItemKeys.OAK_CHEST_BOAT))
            .add(items.getOrThrow(ItemKeys.BAMBOO_CHEST_RAFT))
            .add(items.getOrThrow(ItemKeys.OAK_DOOR))
            .add(items.getOrThrow(ItemKeys.IRON_DOOR))
            .add(items.getOrThrow(ItemKeys.OAK_FENCE_GATE))
            .add(items.getOrThrow(ItemKeys.OAK_TRAPDOOR))
            .add(items.getOrThrow(ItemKeys.IRON_TRAPDOOR))
            .add(items.getOrThrow(ItemKeys.TNT))
            .add(items.getOrThrow(ItemKeys.REDSTONE_LAMP))
            .add(items.getOrThrow(ItemKeys.BELL))
            .add(items.getOrThrow(ItemKeys.BIG_DRIPLEAF))
            .add(items.getOrThrow(ItemKeys.ARMOR_STAND))
            .add(items.getOrThrow(ItemKeys.REDSTONE_ORE))
            .build()
        );
        registerable.register(ItemGroupEntryProviderKeys.TOOLS_AND_UTILITIES, ItemGroupEntryProvider.builder()
            .add(ItematicItemTags.TOOLS)
            .add(ItematicItemTags.BUCKETS)
            .add(items.getOrThrow(ItemKeys.FISHING_ROD))
            .add(items.getOrThrow(ItemKeys.FLINT_AND_STEEL))
            .add(items.getOrThrow(ItemKeys.FIRE_CHARGE))
            .add(items.getOrThrow(ItemKeys.BONE_MEAL))
            .add(items.getOrThrow(ItemKeys.SHEARS))
            .add(items.getOrThrow(ItemKeys.BRUSH))
            .add(items.getOrThrow(ItemKeys.NAME_TAG))
            .add(items.getOrThrow(ItemKeys.LEAD))
            .add(ItematicItemTags.BUNDLES)
            .add(items.getOrThrow(ItemKeys.COMPASS))
            .add(items.getOrThrow(ItemKeys.RECOVERY_COMPASS))
            .add(items.getOrThrow(ItemKeys.CLOCK))
            .add(items.getOrThrow(ItemKeys.SPYGLASS))
            .add(items.getOrThrow(ItemKeys.MAP))
            .add(items.getOrThrow(ItemKeys.WRITABLE_BOOK))
            .add(items.getOrThrow(ItemKeys.WIND_CHARGE))
            .add(items.getOrThrow(ItemKeys.ENDER_PEARL))
            .add(items.getOrThrow(ItemKeys.ENDER_EYE))
            .add(items.getOrThrow(ItemKeys.ELYTRA))
            .add(flightDuration(items.getOrThrow(ItemKeys.FIREWORK_ROCKET)))
            .add(items.getOrThrow(ItemKeys.SADDLE))
            .add(ItematicItemTags.HARNESSES)
            .add(items.getOrThrow(ItemKeys.CARROT_ON_A_STICK))
            .add(items.getOrThrow(ItemKeys.WARPED_FUNGUS_ON_A_STICK))
            .add(ItematicItemTags.BOATS)
            .add(ItematicItemTags.RAILS)
            .add(ItematicItemTags.MINECARTS)
            .add(InstrumentItemGroupEntry.of(items.getOrThrow(ItemKeys.GOAT_HORN), InstrumentTags.GOAT_HORNS))
            .add(ItematicItemTags.MUSIC_DISCS)
            .build()
        );
        registerable.register(ItemGroupEntryProviderKeys.COMBAT, ItemGroupEntryProvider.builder()
            .add(ItematicItemTags.SWORDS)
            .add(ItematicItemTags.AXES)
            .add(ItematicItemTags.SPEARS)
            .add(items.getOrThrow(ItemKeys.TRIDENT))
            .add(items.getOrThrow(ItemKeys.MACE))
            .add(items.getOrThrow(ItemKeys.SHIELD))
            .add(ItematicItemTags.ARMOR)
            .add(ItematicItemTags.HORSE_ARMOR)
            .add(items.getOrThrow(ItemKeys.WOLF_ARMOR))
            .add(ItematicItemTags.NAUTILUS_ARMOR)
            .add(items.getOrThrow(ItemKeys.TOTEM_OF_UNDYING))
            .add(items.getOrThrow(ItemKeys.TNT))
            .add(items.getOrThrow(ItemKeys.END_CRYSTAL))
            .add(items.getOrThrow(ItemKeys.SNOWBALL))
            .add(ItematicItemTags.EGGS)
            .add(items.getOrThrow(ItemKeys.WIND_CHARGE))
            .add(items.getOrThrow(ItemKeys.BOW))
            .add(items.getOrThrow(ItemKeys.CROSSBOW))
            .add(flightDuration(items.getOrThrow(ItemKeys.FIREWORK_ROCKET)))
            .add(items.getOrThrow(ItemKeys.ARROW))
            .add(items.getOrThrow(ItemKeys.SPECTRAL_ARROW))
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemKeys.TIPPED_ARROW)))
            .build()
        );
        registerable.register(ItemGroupEntryProviderKeys.FOOD_AND_DRINKS, ItemGroupEntryProvider.builder()
            .add(ItematicItemTags.FOOD)
            .add(SuspiciousEffectIngredientItemGroupEntry.of(items.getOrThrow(ItemKeys.SUSPICIOUS_STEW)))
            .add(items.getOrThrow(ItemKeys.MILK_BUCKET))
            .add(items.getOrThrow(ItemKeys.HONEY_BOTTLE))
            .add(ominousBottles(items.getOrThrow(ItemKeys.OMINOUS_BOTTLE)))
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemKeys.POTION)))
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemKeys.SPLASH_POTION)))
            .add(PotionItemGroupEntry.of(items.getOrThrow(ItemKeys.LINGERING_POTION)))
            .build()
        );
        registerable.register(ItemGroupEntryProviderKeys.INGREDIENTS, ItemGroupEntryProvider.builder()
            .add(items.getOrThrow(ItemKeys.COAL))
            .add(items.getOrThrow(ItemKeys.CHARCOAL))
            .add(items.getOrThrow(ItemKeys.RAW_IRON))
            .add(items.getOrThrow(ItemKeys.RAW_COPPER))
            .add(items.getOrThrow(ItemKeys.RAW_GOLD))
            .add(items.getOrThrow(ItemKeys.EMERALD))
            .add(items.getOrThrow(ItemKeys.LAPIS_LAZULI))
            .add(items.getOrThrow(ItemKeys.DIAMOND))
            .add(items.getOrThrow(ItemKeys.ANCIENT_DEBRIS))
            .add(items.getOrThrow(ItemKeys.QUARTZ))
            .add(items.getOrThrow(ItemKeys.AMETHYST_SHARD))
            .add(items.getOrThrow(ItemKeys.RESIN_CLUMP))
            .add(ItematicItemTags.NUGGETS)
            .add(items.getOrThrow(ItemKeys.IRON_INGOT))
            .add(items.getOrThrow(ItemKeys.COPPER_INGOT))
            .add(items.getOrThrow(ItemKeys.GOLD_INGOT))
            .add(items.getOrThrow(ItemKeys.NETHERITE_SCRAP))
            .add(items.getOrThrow(ItemKeys.NETHERITE_INGOT))
            .add(items.getOrThrow(ItemKeys.STICK))
            .add(items.getOrThrow(ItemKeys.FLINT))
            .add(items.getOrThrow(ItemKeys.WHEAT))
            .add(items.getOrThrow(ItemKeys.BONE))
            .add(items.getOrThrow(ItemKeys.BONE_MEAL))
            .add(items.getOrThrow(ItemKeys.STRING))
            .add(items.getOrThrow(ItemKeys.FEATHER))
            .add(items.getOrThrow(ItemKeys.SNOWBALL))
            .add(ItematicItemTags.EGGS)
            .add(items.getOrThrow(ItemKeys.LEATHER))
            .add(items.getOrThrow(ItemKeys.RABBIT_HIDE))
            .add(items.getOrThrow(ItemKeys.HONEYCOMB))
            .add(items.getOrThrow(ItemKeys.INK_SAC))
            .add(items.getOrThrow(ItemKeys.GLOW_INK_SAC))
            .add(items.getOrThrow(ItemKeys.TURTLE_SCUTE))
            .add(items.getOrThrow(ItemKeys.ARMADILLO_SCUTE))
            .add(items.getOrThrow(ItemKeys.SLIME_BALL))
            .add(items.getOrThrow(ItemKeys.CLAY_BALL))
            .add(items.getOrThrow(ItemKeys.PRISMARINE_SHARD))
            .add(items.getOrThrow(ItemKeys.PRISMARINE_CRYSTALS))
            .add(items.getOrThrow(ItemKeys.NAUTILUS_SHELL))
            .add(items.getOrThrow(ItemKeys.HEART_OF_THE_SEA))
            .add(items.getOrThrow(ItemKeys.FIRE_CHARGE))
            .add(items.getOrThrow(ItemKeys.BLAZE_ROD))
            .add(items.getOrThrow(ItemKeys.BREEZE_ROD))
            .add(items.getOrThrow(ItemKeys.HEAVY_CORE))
            .add(items.getOrThrow(ItemKeys.NETHER_STAR))
            .add(items.getOrThrow(ItemKeys.ENDER_PEARL))
            .add(items.getOrThrow(ItemKeys.ENDER_EYE))
            .add(items.getOrThrow(ItemKeys.SHULKER_SHELL))
            .add(items.getOrThrow(ItemKeys.POPPED_CHORUS_FRUIT))
            .add(items.getOrThrow(ItemKeys.ECHO_SHARD))
            .add(items.getOrThrow(ItemKeys.DISC_FRAGMENT_5))
            .add(ItematicItemTags.DYES)
            .add(items.getOrThrow(ItemKeys.BOWL))
            .add(items.getOrThrow(ItemKeys.BRICK))
            .add(items.getOrThrow(ItemKeys.NETHER_BRICK))
            .add(items.getOrThrow(ItemKeys.RESIN_BRICK))
            .add(items.getOrThrow(ItemKeys.PAPER))
            .add(items.getOrThrow(ItemKeys.BOOK))
            .add(items.getOrThrow(ItemKeys.FIREWORK_STAR))
            .add(ItematicItemTags.BREWING_INGREDIENTS)
            .add(ItematicItemTags.BANNER_PATTERNS)
            .add(ItemTags.DECORATED_POT_SHERDS)
            .add(ItematicItemTags.SMITHING_TEMPLATES)
            .add(items.getOrThrow(ItemKeys.EXPERIENCE_BOTTLE))
            .add(items.getOrThrow(ItemKeys.TRIAL_KEY))
            .add(items.getOrThrow(ItemKeys.OMINOUS_TRIAL_KEY))
            .add(EnchantmentItemGroupEntry.of(items.getOrThrow(ItemKeys.ENCHANTED_BOOK)))
            .build()
        );
        registerable.register(ItemGroupEntryProviderKeys.SPAWN_EGGS, ItemGroupEntryProvider.builder()
            .add(ItematicItemTags.SPAWNERS)
            .add(items.getOrThrow(ItemKeys.CREAKING_HEART))
            .add(items.getOrThrow(ItemKeys.ALLAY_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.ARMADILLO_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.AXOLOTL_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.BAT_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.BEE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.BLAZE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.BOGGED_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.BREEZE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.CAMEL_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.CAMEL_HUSK_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.CAT_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.CAVE_SPIDER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.CHICKEN_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.COD_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.COPPER_GOLEM_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.COW_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.CREAKING_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.CREEPER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.DOLPHIN_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.DONKEY_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.DROWNED_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.ELDER_GUARDIAN_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.ENDERMAN_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.ENDERMITE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.EVOKER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.FOX_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.FROG_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.GHAST_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.GLOW_SQUID_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.GOAT_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.GUARDIAN_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.HAPPY_GHAST_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.HOGLIN_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.HORSE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.HUSK_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.IRON_GOLEM_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.LLAMA_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.MAGMA_CUBE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.MOOSHROOM_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.MULE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.NAUTILUS_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.OCELOT_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.PANDA_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.PARCHED_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.PARROT_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.PHANTOM_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.PIG_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.PIGLIN_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.PIGLIN_BRUTE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.PILLAGER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.POLAR_BEAR_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.PUFFERFISH_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.RABBIT_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.RAVAGER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.SALMON_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.SHEEP_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.SHULKER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.SILVERFISH_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.SKELETON_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.SKELETON_HORSE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.SLIME_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.SNIFFER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.SNOW_GOLEM_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.SPIDER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.SQUID_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.STRAY_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.STRIDER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.TADPOLE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.TRADER_LLAMA_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.TROPICAL_FISH_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.TURTLE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.VEX_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.VILLAGER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.VINDICATOR_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.WANDERING_TRADER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.WARDEN_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.WITCH_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.WITHER_SKELETON_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.WOLF_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.ZOGLIN_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.ZOMBIE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.ZOMBIE_HORSE_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.ZOMBIE_NAUTILUS_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.ZOMBIE_VILLAGER_SPAWN_EGG))
            .add(items.getOrThrow(ItemKeys.ZOMBIFIED_PIGLIN_SPAWN_EGG))
            .build()
        );
        registerable.register(ItemGroupEntryProviderKeys.OP_BLOCKS, ItemGroupEntryProvider.builder()
            .add(ItemGroupEntry.requiresPermissions(items.getOrThrow(ItemKeys.COMMAND_BLOCK)))
            .add(ItemGroupEntry.requiresPermissions(items.getOrThrow(ItemKeys.CHAIN_COMMAND_BLOCK)))
            .add(ItemGroupEntry.requiresPermissions(items.getOrThrow(ItemKeys.REPEATING_COMMAND_BLOCK)))
            .add(ItemGroupEntry.requiresPermissions(items.getOrThrow(ItemKeys.COMMAND_BLOCK_MINECART)))
            .add(ItemGroupEntry.requiresPermissions(items.getOrThrow(ItemKeys.JIGSAW)))
            .add(ItemGroupEntry.requiresPermissions(items.getOrThrow(ItemKeys.STRUCTURE_BLOCK)))
            .add(ItemGroupEntry.requiresPermissions(items.getOrThrow(ItemKeys.STRUCTURE_VOID)))
            .add(ItemGroupEntry.requiresPermissions(items.getOrThrow(ItemKeys.BARRIER)))
            .add(ItemGroupEntry.requiresPermissions(items.getOrThrow(ItemKeys.DEBUG_STICK)))
            .add(ItemGroupEntry.requiresPermissions(items.getOrThrow(ItemKeys.TEST_INSTANCE_BLOCK)))
            .add(testBlocks(items.getOrThrow(ItemKeys.TEST_BLOCK)))
            .add(lightBlocks(items.getOrThrow(ItemKeys.LIGHT)))
            .add(PaintingVariantItemGroupEntry.unexpected(items.getOrThrow(ItemKeys.PAINTING), PaintingVariantTags.PLACEABLE))
            .build()
        );
    }

    private static ItemGroupEntry[] flightDuration(RegistryEntry<Item> item) {
        List<ItemGroupEntry> entries = new ArrayList<>();
        for (byte flight : FireworkRocketItem.FLIGHT_VALUES) {
            entries.add(StackItemGroupEntry.builder(item)
                .components(ComponentChanges.builder()
                    .add(DataComponentTypes.FIREWORKS, new FireworksComponent(flight, List.of())))
                .build()
            );
        }

        return entries.toArray(ItemGroupEntry[]::new);
    }

    private static ItemGroupEntry[] testBlocks(RegistryEntry<Item> item) {
        List<ItemGroupEntry> entries = new ArrayList<>(TestBlockMode.values().length);
        for (TestBlockMode mode : TestBlockMode.values()) {
            entries.add(StackItemGroupEntry.fromStack(
                TestBlock.applyBlockStateToStack(
                    new ItemStack(item),
                    mode
                ),
                true
            ));
        }

        return entries.toArray(ItemGroupEntry[]::new);
    }

    private static ItemGroupEntry[] lightBlocks(RegistryEntry<Item> item) {
        List<ItemGroupEntry> entries = new ArrayList<>(LightBlock.field_33722);
        for (int level = LightBlock.field_33722; level >= 0; --level) {
            entries.add(StackItemGroupEntry.fromStack(
                LightBlock.addNbtForLevel(
                    new ItemStack(item),
                    level
                ),
                true
            ));
        }

        return entries.toArray(ItemGroupEntry[]::new);
    }

    private static ItemGroupEntry[] ominousBottles(RegistryEntry<Item> item) {
        List<ItemGroupEntry> entries = new ArrayList<>(OminousBottleAmplifierComponent.MAX_VALUE - OminousBottleAmplifierComponent.MIN_VALUE + 1);
        for (int amplifier = OminousBottleAmplifierComponent.MIN_VALUE; amplifier <= OminousBottleAmplifierComponent.MAX_VALUE; amplifier++) {
            ItemStack stack = new ItemStack(item);
            stack.set(DataComponentTypes.OMINOUS_BOTTLE_AMPLIFIER, new OminousBottleAmplifierComponent(amplifier));
            entries.add(StackItemGroupEntry.fromStack(stack));
        }

        return entries.toArray(ItemGroupEntry[]::new);
    }
}
